In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.mixture import GaussianMixture

import warnings
warnings.filterwarnings('ignore')

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

In [2]:
campaign_table = pd.read_csv("../dunnhumby_The-Complete-Journey/campaign_table.csv")
campaign_desc = pd.read_csv("../dunnhumby_The-Complete-Journey/campaign_desc.csv")
coupon_redempt = pd.read_csv("../dunnhumby_The-Complete-Journey/coupon_redempt.csv")
coupon = pd.read_csv("../dunnhumby_The-Complete-Journey/coupon.csv")
transaction_data = pd.read_csv("../dunnhumby_The-Complete-Journey/transaction_data.csv")
product = pd.read_csv("../dunnhumby_The-Complete-Journey/product.csv")
causal = pd.read_csv("../dunnhumby_The-Complete-Journey/causal_data.csv")
segmented_data = pd.read_csv("../dunnhumby_The-Complete-Journey/segmented_df.csv")

In [3]:
product.head()

,PRODUCT_ID,MANUFACTURER,DEPARTMENT,BRAND,COMMODITY_DESC,SUB_COMMODITY_DESC,CURR_SIZE_OF_PRODUCT
0,25671,2,GROCERY,National,FRZN ICE,ICE - CRUSHED/CUBED,22 LB
1,26081,2,MISC. TRANS.,National,NO COMMODITY DESCRIPTION,NO SUBCOMMODITY DESCRIPTION,
2,26093,69,PASTRY,Private,BREAD,BREAD:ITALIAN/FRENCH,
3,26190,69,GROCERY,Private,FRUIT - SHELF STABLE,APPLE SAUCE,50 OZ
4,26355,69,GROCERY,Private,COOKIES/CONES,SPECIALTY COOKIES,14 OZ

In [4]:
product.drop(product[product['SUB_COMMODITY_DESC'].str.strip() == ''].index, inplace=True)

In [5]:
txn_product_merged = transaction_data.merge(
    product[
        [
            "PRODUCT_ID",
            "COMMODITY_DESC",
            "SUB_COMMODITY_DESC",
            "DEPARTMENT"
        ]
    ],
    on="PRODUCT_ID",
    how="left"
)

In [6]:
transaction_data.isnull().sum()

household_key        0
BASKET_ID            0
DAY                  0
PRODUCT_ID           0
QUANTITY             0
SALES_VALUE          0
STORE_ID             0
RETAIL_DISC          0
TRANS_TIME           0
WEEK_NO              0
COUPON_DISC          0
COUPON_MATCH_DISC    0
dtype: int64

In [7]:
txn_product_merged.shape

(2595732, 15)

In [8]:
txn_product_merged.isnull().sum()

household_key            0
BASKET_ID                0
DAY                      0
PRODUCT_ID               0
QUANTITY                 0
SALES_VALUE              0
STORE_ID                 0
RETAIL_DISC              0
TRANS_TIME               0
WEEK_NO                  0
COUPON_DISC              0
COUPON_MATCH_DISC        0
COMMODITY_DESC        7839
SUB_COMMODITY_DESC    7839
DEPARTMENT            7839
dtype: int64

In [9]:
txn_product_merged = txn_product_merged.dropna()

In [10]:
txn_product_merged.head()

,household_key,BASKET_ID,DAY,PRODUCT_ID,QUANTITY,SALES_VALUE,STORE_ID,RETAIL_DISC,TRANS_TIME,WEEK_NO,COUPON_DISC,COUPON_MATCH_DISC,COMMODITY_DESC,SUB_COMMODITY_DESC,DEPARTMENT
0,2375,26984851472,1,1004906,1,1.39,364,-0.60,1631,1,0.0,0.0,POTATOES,POTATOES RUSSET (BULK&BAG),PRODUCE
1,2375,26984851472,1,1033142,1,0.82,364,0.00,1631,1,0.0,0.0,ONIONS,ONIONS SWEET (BULK&BAG),PRODUCE
2,2375,26984851472,1,1036325,1,0.99,364,-0.30,1631,1,0.0,0.0,VEGETABLES - ALL OTHERS,CELERY,PRODUCE
3,2375,26984851472,1,1082185,1,1.21,364,0.00,1631,1,0.0,0.0,TROPICAL FRUIT,BANANAS,PRODUCE
4,2375,26984851472,1,8160430,1,1.50,364,-0.39,1631,1,0.0,0.0,ORGANICS FRUIT & VEGETABLES,ORGANIC CARROTS,PRODUCE

In [11]:
txn_product_merged["SUB_COMMODITY_DESC"].nunique()

2382

In [12]:
sub_commodity_purchases = (
    txn_product_merged
    .groupby(
        [
            "household_key",
            "SUB_COMMODITY_DESC"
        ]
    )
    .agg(
        total_quantity=("QUANTITY", "sum"),
        total_sales=("SALES_VALUE", "sum")
    )
    .reset_index()
)

In [13]:
sub_commodity_purchases.head()

   household_key   SUB_COMMODITY_DESC  total_quantity  total_sales
0              1     ADULT ANALGESICS               3        16.67
1              1         ADULT CEREAL               2         7.48
2              1     AEROSOL TOPPINGS               1         1.99
3              1  AIR CARE - AEROSOLS               1         2.99
4              1   AIR CARE - CANDLES               6        16.73

In [14]:
sub_commodity_purchases.shape

(614459, 4)

In [15]:
sub_commodity_purchases.isnull().sum()

household_key         0
SUB_COMMODITY_DESC    0
total_quantity        0
total_sales           0
dtype: int64

In [16]:
sub_commodity_purchases['SUB_COMMODITY_DESC'].value_counts()

SUB_COMMODITY_DESC
FLUID MILK WHITE ONLY             2392
BANANAS                           2105
SOFT DRINKS 12/18&15PK CAN CAR    2059
POTATO CHIPS                      2046
SHREDDED CHEESE                   2031
PREMIUM                           1984
SFT DRNK 2 LITER BTL CARB INCL    1976
MAINSTREAM WHITE BREAD            1960
EGGS - LARGE                      1937
CANDY BARS (SINGLES)(INCLUDING    1909
TORTILLA/NACHO CHIPS              1882
POURABLE SALAD DRESSINGS          1864
DAIRY CASE 100% PURE JUICE - O    1858
TOILET TISSUE                     1830
CONDENSED SOUP                    1802
SEMI-SOLID SALAD DRESSING MAY     1780
PRIMAL                            1775
SUGAR                             1775
IWS SINGLE CHEESE                 1773
SPICES & SEASONINGS               1773
HAMBURGER BUNS                    1743
MARGARINE: TUBS AND BOWLS         1740
POTATOES RUSSET (BULK&BAG)        1715
ALL FAMILY CEREAL                 1708
EGGS - X-LARGE                    1682
MAINSTREAM WHEAT/MULTIGRAIN BR    1680
KIDS CEREAL                       1680
HOT DOG BUNS                      1642
CREAM CHEESE                      1638
BEERALEMALT LIQUORS               1628
CHOICE BEEF                       1623
SOUR CREAMS                       1607
CATSUP                            1605
PEANUT BUTTER                     1597
PAPER TOWELS & HOLDERS            1595
YOGURT NOT MULTI-PACKS            1582
MAINSTREAM                        1579
SPAGHETTI DRY                     1563
SNACK CAKE - MULTI PACK           1559
SNACKS/APPETIZERS                 1530
LIQUID LAUNDRY DETERGENTS         1510
CHEWING GUM                       1497
SFT DRNK SNGL SRV BTL CARB (EX    1494
LEAN                              1489
NOODLES DRY                       1466
SOUP CRACKERS (SALTINE/OYSTER)    1462
ADULT CEREAL                      1460
STRAWBERRIES                      1460
SMOKED/COOKED                     1459
FRZN BAGGED VEGETABLES - PLAIN    1458
CHEESE CRACKERS (CHEEZ-ITS/GOL    1445
TUNA                              1444
CORN                              1438
GASOLINE-REG UNLEADED             1438
MACARONI & CHEESE DNRS            1427
SWEET GOODS - FULL SIZE           1422
MEXICAN SAUCESSALSAPICANTEE       1419
NON-CRBNTD DRNKING/MNERAL WATE    1417
SW GDS:DONUTS                     1417
HEAD LETTUCE                      1402
PRETZELS                          1399
BEANS GREEN: FS/WHL/CUT           1386
RTS SOUP: CHUNKY/HOMESTYLE ET     1383
BUTTER SPRAY CRACKER (RITZ/CLU    1380
POULTRY                           1363
CHICKEN BREAST BONELESS           1358
ENHANCED                          1358
CARROTS MINI PEELED               1358
ONIONS SWEET (BULK&BAG)           1347
FRZN BREADED PREPARED CHICK       1342
CARDS EVERYDAY                    1327
NATURAL CHEESE EXACT WT CHUNKS    1318
GRAPES RED                        1317
SS ECONOMY ENTREES/DINNERS ALL    1311
FRZN GARLIC BREAD/TOAST/STICKS    1311
HAM                               1307
BBQ SAUCE                         1307
PICKLES                           1306
TOOTHPASTE                        1297
PREPARED BEANS - BAKED W/PORK     1297
VARIETY BEANS - KIDNEY PINTO      1295
CANDY BARS (MULTI PACK)           1295
COTTAGE CHEESE                    1294
TRADITIONAL                       1287
CELERY                            1277
GRAPES WHITE                      1277
MOLASSES & SYRUPS                 1275
FRZN MULTI SERVE ENTREES ALL      1264
PEPPERS GREEN BELL                1257
FRZN FRENCH FRIES                 1255
MEAT: TURKEY BULK                 1255
LIQUID DISH DETERGENT             1254
CANDY BAGS-CHOCOCLATE             1252
REGULAR GARDEN                    1251
REFRIGERATED BISCUITS REGULAR     1244
PREMIUM - MEAT                    1239
PASTA: CANNED                     1238
BOLOGNA                           1226
SANDWICH COOKIES                  1225
RICE SIDE DISH MIXES DRY          1221
MACARONI DRY                      1198
FRZN SS PREMIUM ENTREES/DNRS/T    1197
STICKS/ENROBED                    1196
SPRING WATER                      1196
SFT DRNK MLT-PK BTL CARB (EXCP    1194
SHAMPOO                           1192
TOMATOES: STEWED/DICED/CRMD       1188
TOMATOES VINE RIPE BULK           1182
SALAD MUSTARD                     1177
TRAY PACK/CHOC CHIP COOKIES       1177
CHOCOLATE MILK                    1175
LAYER CAKE MIX                    1173
VEGETABLE/SALAD OIL               1173
SNACK CRACKERS                    1166
POPCORN - MICROWAVE               1160
CANISTER POTATO/TORT CHIPS        1157
ORANGES NAVELS ALL                1155
CUCUMBERS                         1155
ALUMINUM FOIL                     1153
MEAT:HAM BULK                     1153
SEASONAL CANDY BAGS-CHOCOLATE     1139
WAFFLES/PANCAKES/FRENCH TOAST     1138
SALAD BAR FRESH FRUIT             1130
CANDY BAGS-NON CHOCOLATE          1130
SOFT DRINK POWDER POUCHES         1124
ADULT ANALGESICS                  1122
PIZZA/PREMIUM                     1121
SANDWICHES&HANDHELDS              1115
FRUIT BOWL AND CUPS               1112
PEPPERONI/SALAMI                  1109
FROSTING                          1109
TOASTER PASTRIES                  1106
SOFT DRINKS 20PK&24PK CAN CARB    1106
PINEAPPLE                         1105
DAIRY CASE JUICE DRNK UNDER 10    1105
EGGS - MEDIUM                     1102
TOMATOES HOTHOUSE ON THE VINE     1102
RAMEN NOODLES/RAMEN CUPS          1098
ECONOMY                           1093
YOGURT MULTI-PACKS                1088
FRZN WHIPPED TOPPING              1085
SAUCE MIXES GRAVY MIXES DRY       1077
BAGGED CHEESE SNACKS              1072
MARGARINE  STICK                  1071
ROLLS - PORK                      1066
GARDEN PLUS                       1065
REFRIGERATED SPECILATY ROLLS      1064
GROUND COFFEE                     1061
FACIAL TISSUE & PAPER HANDKE      1047
BLENDS                            1046
ASEPTIC PACK JUICE AND DRINKS     1044
INSTORE CUT FRUIT                 1034
CHILI: CANNED                     1032
MISCELLANEOUS CANDY (INCLUDING    1032
WATER ICE                         1031
FLOUR: WHITE & SELF RISING        1028
CHEESE: NATURAL BULK              1021
PIZZA/TRADITIONAL                 1018
COOKIES: REGULAR                  1013
POTATOES: DRY                     1011
MUFFIN & CORN BREAD MIX           1007
ONIONS WHITE (BULK&BAG)           1004
CORN CHIPS                        1004
INSTANT OATMEAL                   1002
ISOTONIC DRINKS SINGLE SERVE      1002
CIGARETTES                         998
PRESERVES JAM MARMALADE            997
GARBAGE KITCHEN COMPACTOR BA       996
MEXICAN SEASONING MIXES            991
DIPS (NON-REFRIGERATED)            991
LIQUID BLEACH                      987
MISCELLANEOUS                      983
CHICKEN BREAST BONE IN             983
BUTTER                             983
STUFFING MIXES                     982
SELECT BEEF                        978
SKILLET DINNERS                    975
REFRIG DIPS                        972
FRZN SS PREMIUM ENTREES/DNRS/N     967
ONIONS YELLOW (BULK&BAG)           963
JELLY                              963
SGL SV/VEND MACH SNACKS CHIP/P     962
PIZZA/ECONOMY                      959
BREAD:ITALIAN/FRENCH               957
APPLES RED DELICIOUS (BULK&BAG     953
ALKALINE BATTERIES                 951
TOMATO SAUCE                       947
STEAK & WORCHESTER SAUCE           946
BROTH                              939
GADGETS/TOOLS                      937
BAR SOAP                           935
GRANOLA BARS                       929
GRATED CHEESE                      920
ONIONS OTHER                       916
REFRIGERATED PUDDING               908
BREAST - BONELESS(IQF)             908
PLSTC CTLRYTBLCLTHSTTHPKSST        907
MISC SALES TRANS                   903
ECONOMY - MEAT                     899
VANILLA WAFER/KIDS COOKIES         897
MALTED MLK/SYRUP/PWDRS (EGGNOG     893
FRUIT SNACKS                       891
CANTALOUPE WHOLE                   889
NO SUBCOMMODITY DESCRIPTION        884
PAPER NAPKINS                      883
BETTER FOR YOU                     876
BROCCOLI WHOLE&CROWNS              874
NOODLE SIDE DISH MIXES             872
ICE - CRUSHED/CUBED                871
STRING CHEESE                      869
REFRIGERATED COOKIES-CHUB          865
FRZN BOXED VEGETABLES- VALUE A     864
PEACHES YELLOW FLESH               862
ENTREES                            862
BAGELS                             861
APPLES GALA (BULK&BAG)             859
FEM. HYGN.NAPKINS                  858
GRND/PATTY - FROZEN                855
SOLID/STK DEODORANTS               853
HAIR CONDITIONERS AND RINSES       849
NATURAL CHEESE EXACT WT SLICES     847
PREMIUM PINTS                      846
MARSHMALLOWS                       846
APPLE JUICE & CIDER (OVER 50%      846
PEAS GREEN                         843
BROWNIE MIX                        840
MINTS CANDY & BREATH (NOT LIF      837
ICE CREAM SANDWICHES               834
CONES                              834
CARDS SEASONAL                     830
CROUTONS SALAD TOPPERS BREAD       828
CEREAL BARS                        827
COOKING SPRAYS                     825
RAZORS AND BLADES                  818
PREMIUM BREAD                      816
LINKS - RAW                        814
REFRIGERATED MEXICAN PRODUCTS      813
VAC PAC NUTS(CANS)                 808
DISPOSABLE FOILWARE                805
NEWSPAPER                          804
PUDDING&GELATIN CUPS/CANS          803
APPLES OTHER (BULK&BAG)            802
FRZN BRD STICK/PORTON              799
LUNCH COMBO                        789
SANDWICH BAGS                      788
PUDDINGS DRY                       788
HOT SAUCE                          784
SOFT DRINKS 6PK/4PK CAN CARB (     783
LEMONS                             782
POTATOES RED (BULK&BAG)            779
MEXICAN SOFT TORTILLAS AND WRA     779
GRAVY CAN/GLASS                    779
DRY SOUP                           779
MISCELLANEOUS CHEESE               778
VEGETABLE SALADS - PREPACK         778
PATTIES                            777
FRZN BREAKFAST ENTREES/SANDWIC     776
INSIDE FROST BULBS                 774
RICE - INSTANT & MICROWAVE         771
SOFT DRINK BOTTLE NON-CARB (EX     760
CABBAGE                            759
PEACHES                            754
SANDWICH BUNS                      753
TOMATOES GRAPE                     750
ORAL HYGIENE BRUSHES               748
BODY WASH                          748
BREADINGS  COATINGS CRUMBS         745
LOAF CHEESE                        743
TABLE SALT POPCORN SALTICE C       742
RIBS                               740
GRAHAM CRACKERS                    736
FRESH                              735
ANTI-ACIDS                         734
LIQUID SOAP                        733
PANCAKE MIXES                      733
REFRIGERATED COFFEE CREAMERS       732
MISCELLANEOUS MILK                 729
APPLES GRANNY SMITH (BULK&BAG)     729
CORN YELLOW                        729
SEASONAL MISCELLANEOUS             726
BITS & MORSELS                     726
APPLES GOLD DELICIOUS (BULK&BA     723
FABRIC SOFTENER SHEETS             723
TEA BAGS & BULK TEA                717
MULTI-PACK CRACKERS                715
VINEGAR ALL-EXCEPT WINE/RIC        714
HOT CHOCOLATE COCOA MIX            711
MELON HALVES/QUARTERS              708
ANGUS                              708
MISC BAG SNACKS                    707
SPECIALTY COOKIES                  698
VARIETY LETTUCE                    697
MEAT: SAUS DRY BULK                697
ROLLS: DINNER                      696
RELISHES                           696
ANTIPERSPIRANTS ONLY (ALL OTHE     696
FREEZER BAGS                       687
COUGH SYRP/LOZNG-DRP/XPCTRNT       686
POTATOES SWEET&YAMS                685
BAKING NUTS                        677
CHICKEN DRUMS                      673
COLD AND FLU - DXM                 673
FRZN BOXED VEGETABLES - PLAIN      669
NATURAL BEEF                       668
CHIX: ROTISSERIE (HOT)             667
COLD AND FLU                       667
SW GDS: SW ROLLS/DAN               664
ROMA TOMATOES (BULK/PKG)           664
PREP FD: SIDE DISHES (HOT)         664
FOAM PLATES                        663
FOOD STORAGE BAGS                  663
NON DAIRY CREAMER: DRY             659
FRUIT COCKTAIL FRUIT SALAD         658
PEPPERS RED BELL                   658
RAISINS                            657
MEAT: LUNCHMEAT BULK               656
FEM. HYGN. TAMPONS                 656
PIES: FRUIT/NUT                    655
PLASTIC CUPS                       655
GELATIN                            654
DIPS                               653
WATERMELON SEEDLESS WHOLE          650
MUSHROOMS CND & GLASS              649
NON-CARB FLVRD DRNKNG/MNRL WAT     648
COFFEE FILTERS                     648
MEAT SUPPLIES                      647
CAKES: LAYERS                      646
LOIN - CHOPS BONELESS              644
CANNED MILK                        644
TOMATO PASTE                       641
ENGLISH MUFFINS/WAFFLES            639
MEAT: BEEF BULK                    638
APPLE SAUCE                        634
STANDARD OATMEAL                   633
SUPER PREMIUM PINTS                632
BABY DIAPERS                       632
WHOLE CHICKEN (ROASTERS/FRYER)     631
PLUMS                              631
FRZN BAGGED VEGETABLES- VALUE      630
CARROTS BAGGED                     628
MEXICAN DINNERS AND FOODS          626
PREMIUM - BEEF                     625
FRZN TATER TOTS/OTHER EXTRUDED     621
PREMIUM COOKIES (EX: PEPPERIDG     620
CAKES: NOVELTIES                   618
FABRIC SOFTENER LIQUID             617
RICE - DRY BAG AND BOX             616
CHEESE: PROCESSED BULK             614
SANDWICH SAUCE                     613
MANDARIN ORANGES/CITRUS SECT       612
BAGGED POPPED POPCORN              611
ONIONS RED (BULK&BAG)              611
DINNER ROLLS                       608
MOUTHWASH RINSES AND SPRAYS        606
CHOCOLATE COVERED COOKIES          605
AEROSOL TOPPINGS                   604
MEXICAN TACO TOSTADO SHELLS        602
HOT MUSTARD/SPECIALTY MUSTAR       600
OLIVE OIL                          595
TAPE & MAILING PRODUCTS            595
SEAFOOD-FRZ-IQF RAW SHRIMP RW      590
BLENDED JUICE&COMBINATIONS (OV     588
SOFT DRINKS CAN NON-CARB (EXCE     587
SNACK MIX                          585
CRANBERRY JUICE (50% AND UNDER     583
ASPARAGUS                          582
FRZN HASHBROWN POTATOES            578
MISC MEAT SAUCES                   577
SHAVE CREAMS AND POWDERS           577
PLASTIC TRASH BAGS                 575
SOUP/STEW                          574
DRY BEANS/PEAS/BARLEY: BAG & B     574
TEA SWEETENED                      573
SEASONAL CANDY BAGS NON-CHOCOL     572
CRANAPPLE CRAN GRAPE JUICE (5      571
CANOLA OILS                        566
GRAPE JUICE (OVER 50% JUICE)       563
MEXICAN BEANS REFRIED              562
BABY WIPES                         560
SINUS AND ALLERGY                  560
BLENDED JUICE&COMBINATIONS (50     558
JUICE (UNDER 10% JUICE)            557
SEAFOOD-FRZ-RAW FILLETS            556
ICE CREAM TOPPINGS                 555
AIR CARE - CONTINUOUS ACTION       554
BLUEBERRIES                        553
HAIR SETS AND GELS                 550
DISPOSABLE FD STORAGE CONTAINR     549
BAKING POWDER & SODA               548
ROLLS: SANDWICH                    546
TOMATOES VINE RIPE PKG             542
VEG JUICE (EXCEPT TOMATO) (OVE     541
LIPCARE                            540
DAIRY CASE 100% PURE JUICE OTH     540
SWEETENERS                         538
VEGETABLES ALL OTHER               536
CORN DOGS                          536
SPONGES: BATH HOUSEHOLD            536
PANTRY                             535
BASIC PAPER PLATES                 534
GREEN OLIVES                       534
GARLIC WHOLE CLOVES                534
PEARS                              531
DAIRY CASE CITRUS PNCH/OJ SUBS     531
REFRIGERATED COOKIES-BREAK N B     529
LIMES                              529
CAKE DECORS & ICING                529
ISOTONIC DRINKS MULTI-SERVE        527
RYE BREADS                         522
PLASTIC/HEAVY PAPER PREM PLATE     521
SOFT DRINK CANISTERS               519
MISCELLANEOUS PACKAGE MIXES        518
GUM (PACKAGED)                     515
RIPE OLIVES                        513
MUSHROOMS W/WHOLE PKG              512
FRUIT DRINKS: CANNED & GLASS (     511
POTATOES OTHER                     510
VARIETY PACK                       509
HONEY                              508
WRITING INSTRUMENTS                508
CHICKEN THIGHS                     507
NECTARINES YELLOW FLESH            506
DRIED FRUIT - OTHER                505
DRY CAT FOOD (CAT CHOW/FRISKIE     504
AIR CARE - AEROSOLS                503
CRANBERRY SAUCE                    503
CLEANING WIPES                     502
BREAD:SAVORY/SPECIALTY             502
FROZEN FRUIT PIES  & COBBLERS      501
BATHROOM CLEANERS - GENERAL        500
MUSHROOMS WHITE SLICED PKG         500
MISCELLANEOUS VEGETABLES           497
WOMEN S GENERAL-MAGAZINE           494
COOKIES: HOLIDAY/SPECIAL OCCAS     493
PIE FILLING MINCEMEAT GLAZES       493
CAULIFLOWER WHOLE                  493
HAND AND BODY LOTIONS              492
TEA BAGS HERBAL & FLAVORED         492
PICKLD VEG PEPPERS ETC             488
CHIX:FRD 8PC/CUT UP (HOT)          485
MULTI-PACK COOKIES                 485
WINGS (IQF)                        484
SCHOOL PAPER                       484
BANDAGE/TAPE                       484
DIET/LIGHT BREAD                   482
PRODUCE DEPT KEY RING              481
BURRITOS                           481
CHARCOAL                           480
MISCELLANEOUS H & B AIDS           480
MISC REFRIG DOUGH PRODUCTS         478
SPINACH & GREENS                   476
DRESSINGS                          476
CHERRIES RED                       472
GIFT-WRAP EVERYDAY                 472
REFRIGERATED BAGELS                471
DAIRY CASE FRUIT DRINKS (NO JU     468
COVERGIRL                          467
BISCUIT FLOUR & MIXES              466
CHEESE:SPECIALTY PREPACK           466
DRY                                465
VALUE                              461
LAXATIVES                          459
ENERGY DRINK                       459
TV/MOVIE-MAGAZINE                  459
POTATOES SWEET                     457
GRAPEFRUIT                         456
SOIL & STAIN REMOVER               456
SNACK NUT(BAG)                     455
SANDWICH SAUCE HORSERADISH SA      455
CANDY BARS MULTI PACK W/FLOUR      454
PATTIES - RAW                      453
SALAD SPINACH                      452
BEANS                              451
ORIENTAL OTHER SAUCES MARINAD      450
KOSHER/SPECIALTY                   449
PLASTIC WRAP (SARANETC.)           448
DESIGNER PAPER: MEDIUM WEIGHT      447
FRZN BREAKFAST PASTRY              447
PORK-FULLY COOKED                  447
CHEESE: NATURAL PREPORTND          446
SCOURING PADS & CLOTH              445
SAUERKRAUT                         445
COUPONS/STORE & MFG                442
DRY DOG FOOD PREMIUM (ALPO/PUR     442
BABY FOOD - BEGINNER               439
FRZN BURGERS/BBQ/MEATBALL          437
METAL BAKEWARE                     435
MAYBELLINE                         434
SAL:SALSA/DPS-PRPCK                434
ROLLS - FLAVORED/OTHER             433
CUT VEGETABLES ALL OTHER           433
TOILET BOWL MANUAL                 432
SANDWICHES/BISCUITS/GRAVY          431
SEAFOOD-FRE-NON RW-ALL             431
LINAMENTS                          430
GRAPES BLACK/BLUE                  429
MISC SNACKS                        428
SOLID SHORTENING                   427
HOT DOG CHILI SAUCE                427
PIZZA SAUCE                        425
AUTO DISH DETERGENT - GEL          425
SW GDS:COFFEE CAKES                424
CUPS/PUSH UPS/OTHER                423
SQUASH ZUCCHINI                    422
FACIAL SOAPS-SCRUBS-MASKS          422
FLAVORED/OTHER                     420
ORGANIC CARROTS                    420
ORIENTAL SOY SAUCE                 417
RICE CAKES                         416
PAILS                              416
FROZEN FRUIT                       415
PIZZA/SINGLE SERVE/MICROWAVE       413

In [17]:
sub_commodity_freq = (
    sub_commodity_purchases
    .groupby("SUB_COMMODITY_DESC")
    .size()
    .sort_values(ascending=True)
)

sub_commodity_freq.head(50)

SUB_COMMODITY_DESC
*ATH ACCES:TOWEL BARS/SOAP D      1
HANDHELD EQUIPMENT                1
VASES                             1
ARBOR/TRELLIS                     1
ARRANGEMENTS (NON-ROSE)           1
AROMA THERAPY OIL/GELS/CANDLES    1
ULTRA/SUPER GIN                   1
NUT SUPP-ESSENTIAL OILS           1
SOLAR GIFTS                       1
NUT SUPP-INDIVIDUAL               1
NUT SUPP-MISC                     1
DRYWALL REPAIR                    1
SMALL ACCESS LADIES GLOVES        1
SLUG BAITS                        1
CAKES INGREDIENTS                 1
CABINET ACCS: HINGES/KNOBS        1
HH GAMES                          1
LIGHTBULBS                        1
FTD SERVICE CHARGES               1
GARDEN WICKER                     1
CAMERAS                           1
SMOKE DETECTORS                   1
CAMERAS-35MM/APS                  1
LICENSE APPAREL GIRLS 7-16        1
EASTER LILY                       1
NUT SUPP-WELLNESS                 1
NOVELTY LIGHTS                    1
NUT SUPP-CHILDREN                 1
UNIQUE SODAS                      1
UPDATED WOVENS                    1
ORGANIC                           1
ULTRA/SUPER TEQUILA               1
TREES/SHRUBS                      1
TRICYCLES/WAGONS/ETC              1
MISC. SEWING/CRAFTS               1
AUTO BODY PAINT/ADHESIVES         1
MISC/GIFTS                        1
DIET PILLS/SUPPLEMENTS            1
PARTY TRAYS: CAKES                1
ORGANIC BEEF                      1
HOT DOGS-BEEF                     1
MOSQUITO                          1
TOBACCO FREE SNUFF                1
TEA UNSWEETENED (CAN/BOTTLE)      1
BABY PRODUCTS                     1
CRV DEPOSIT NT/F                  1
LUNCHMEAT-RW-ALL                  1
COUPON                            1
PERIPHERALS                       1
PERRENIALS                        1
dtype: int64

In [18]:
# building the household-item matrix
valid_commodities = (
    sub_commodity_freq[
        sub_commodity_freq >= 20
    ].index
)

sub_commodity_purchases = (
    sub_commodity_purchases[
        sub_commodity_purchases["SUB_COMMODITY_DESC"]
        .isin(valid_commodities)
    ]
)

In [19]:
sub_commodity_purchases.shape

(610053, 4)

In [20]:
sub_commodity_purchases["SUB_COMMODITY_DESC"].nunique()

1677

In [21]:
#commodity dataset created

In [22]:
household_txn_agg = (
    txn_product_merged
    .groupby("household_key")
    .agg(
        total_sales=("SALES_VALUE", "sum"),
        total_quantity=("QUANTITY", "sum"),
        total_transactions=("BASKET_ID", "count"),
        unique_sub_commodities=("SUB_COMMODITY_DESC", "nunique")
    )
    .reset_index()
)

household_txn_agg.head()

,household_key,total_sales,total_quantity,total_transactions,unique_sub_commodities
0,1,4330.16,1997,1714,302
1,2,1954.34,834,714,299
2,3,2653.21,8540,921,219
3,4,1200.11,382,301,110
4,5,779.06,245,222,125

In [23]:
household_txn_agg.sort_values(by='unique_sub_commodities', ascending=False).loc[1073
                                                                                ]

household_key               1074.00
total_sales                 7769.22
total_quantity            142911.00
total_transactions          2345.00
unique_sub_commodities       405.00
Name: 1073, dtype: float64

In [24]:
household_txn_agg.sort_values(by='unique_sub_commodities', ascending=False).head(30)

,household_key,total_sales,total_quantity,total_transactions,unique_sub_commodities
1452,1453,21661.29,95743,6540,903
2321,2322,23646.92,992718,5675,882
2458,2459,20671.50,488789,6624,813
1900,1901,11462.24,60290,4048,770
2283,2284,17152.63,185015,4621,762
717,718,19299.86,869732,6782,723
327,328,17332.13,356334,4864,714
1994,1995,15332.43,427801,4465,699
399,400,18494.14,862525,4664,693
1851,1852,9800.02,900726,2634,683
908,909,12414.56,1059350,3501,675
112,113,15324.95,1074819,4406,674
2109,2110,12470.03,284700,3263,666
1652,1653,19153.75,1065654,5328,660
1228,1229,18304.31,1295539,4450,660
2263,2264,16960.59,27358,4424,657
933,934,10709.38,137630,4852,655
370,371,15716.54,7083,5665,651
2192,2193,9155.01,203617,2861,650
1227,1228,14503.89,1085371,3990,647
231,232,12695.57,527603,4014,627
2115,2116,12228.09,495774,4208,627
1313,1314,14330.40,1492863,2826,626
1336,1337,11500.76,791184,4082,624
1974,1975,17548.27,545648,4003,623
1509,1510,11211.37,595975,4811,623
1366,1367,12125.48,1003596,3623,621
1763,1764,11412.20,582818,3014,621
1597,1598,11516.83,204679,3560,619
2488,2489,9403.42,216843,3238,619

In [25]:
sub_commodity_rank = (
    sub_commodity_purchases
    .sort_values(
        [
            "household_key",
            "total_quantity",
            "total_sales"
        ],
        ascending=[True, False, False]
    )
)

In [26]:
sub_commodity_rank.shape

(610053, 4)

In [27]:
sub_commodity_rank.head(20)

,household_key,SUB_COMMODITY_DESC,total_quantity,total_sales
188,1,ORANGES NAVELS ALL,63,37.44
102,1,FRUIT/BREAKFAST BREAD,56,157.05
26,1,BEANS GREEN: FS/WHL/CUT,56,53.98
222,1,PUDDINGS DRY,54,41.03
90,1,ENTREES,48,127.29
45,1,CANDY BAGS-CHOCOCLATE,48,83.57
76,1,DAIRY CASE 100% PURE JUICE - O,46,129.81
251,1,SOFT DRINKS 12/18&15PK CAN CAR,43,121.13
22,1,BANANAS,42,37.74
96,1,FLUID MILK WHITE ONLY,41,61.92
206,1,POTATO CHIPS,40,76.46
262,1,STICKS/ENROBED,36,114.34
293,1,VARIETY BEANS - KIDNEY PINTO,34,35.50
108,1,FRZN WHIPPED TOPPING,33,39.69
124,1,GUM (PACKAGED),30,56.75
66,1,CONDENSED SOUP,28,39.66
34,1,BROTH,26,24.74
202,1,PINEAPPLE,23,26.28
209,1,POULTRY,22,84.55
79,1,DESIGNER PAPER: MEDIUM WEIGHT,21,61.65

In [28]:
top_sub_commodities = (
    sub_commodity_rank
    .groupby("household_key")
    .head(5)
)
top_sub_commodities.head(15)

,household_key,SUB_COMMODITY_DESC,total_quantity,total_sales
188,1,ORANGES NAVELS ALL,63,37.44
102,1,FRUIT/BREAKFAST BREAD,56,157.05
26,1,BEANS GREEN: FS/WHL/CUT,56,53.98
222,1,PUDDINGS DRY,54,41.03
90,1,ENTREES,48,127.29
561,2,SOFT DRINKS 12/18&15PK CAN CAR,40,113.00
525,2,RAMEN NOODLES/RAMEN CUPS,32,3.79
409,2,FLUID MILK WHITE ONLY,22,42.61
590,2,TUNA,16,33.13
327,2,BEANS GREEN: FS/WHL/CUT,12,7.24
678,3,GASOLINE-REG UNLEADED,6949,20.01
777,3,SFT DRNK 2 LITER BTL CARB INCL,82,99.76
643,3,CORN,74,40.71
779,3,SGL SV/VEND MACH SNACKS CHIP/P,72,21.60
725,3,NOODLE SIDE DISH MIXES,55,53.87

In [29]:
top_sub_commodities.shape

(12498, 4)

In [30]:
top_sub_commodity_list = (
    top_sub_commodities
    .groupby("household_key")
    ["SUB_COMMODITY_DESC"]
    .apply(list)
    .reset_index()
)

top_sub_commodity_list.head()

   household_key                                 SUB_COMMODITY_DESC
0              1  [ORANGES NAVELS ALL, FRUIT/BREAKFAST BREAD, BE...
1              2  [SOFT DRINKS 12/18&15PK CAN CAR, RAMEN NOODLES...
2              3  [GASOLINE-REG UNLEADED, SFT DRNK 2 LITER BTL C...
3              4  [PIZZA/ECONOMY, CHEESE CRACKERS (CHEEZ-ITS/GOL...
4              5  [ISOTONIC DRINKS SINGLE SERVE, ISOTONIC DRINKS...

In [31]:
top_sub_commodity_list['SUB_COMMODITY_DESC'][0]

['ORANGES NAVELS ALL',
 'FRUIT/BREAKFAST BREAD',
 'BEANS GREEN: FS/WHL/CUT',
 'PUDDINGS DRY',
 'ENTREES']

In [32]:
household_txn_agg = (
    household_txn_agg
    .merge(
        top_sub_commodity_list,
        on="household_key",
        how="left"
    )
)

household_txn_agg.head()

,household_key,total_sales,total_quantity,total_transactions,unique_sub_commodities,SUB_COMMODITY_DESC
0,1,4330.16,1997,1714,302,"[ORANGES NAVELS ALL, FRUIT/BREAKFAST BREAD, BE..."
1,2,1954.34,834,714,299,"[SOFT DRINKS 12/18&15PK CAN CAR, RAMEN NOODLES..."
2,3,2653.21,8540,921,219,"[GASOLINE-REG UNLEADED, SFT DRNK 2 LITER BTL C..."
3,4,1200.11,382,301,110,"[PIZZA/ECONOMY, CHEESE CRACKERS (CHEEZ-ITS/GOL..."
4,5,779.06,245,222,125,"[ISOTONIC DRINKS SINGLE SERVE, ISOTONIC DRINKS..."

In [33]:
household_txn_agg["sales_spend_tier"] = pd.qcut(
    household_txn_agg["total_sales"],
    q=4,
    labels=[
        "Low",
        "Medium",
        "High",
        "Premium"
    ]
)

In [34]:
household_txn_agg["quantity_tier"] = pd.qcut(
    household_txn_agg["total_quantity"],
    q=4,
    labels=[
        "Low",
        "Medium",
        "High",
        "Premium"
    ]
)

In [35]:
household_txn_agg.head()

,household_key,total_sales,total_quantity,total_transactions,unique_sub_commodities,SUB_COMMODITY_DESC,sales_spend_tier,quantity_tier
0,1,4330.16,1997,1714,302,"[ORANGES NAVELS ALL, FRUIT/BREAKFAST BREAD, BE...",High,Medium
1,2,1954.34,834,714,299,"[SOFT DRINKS 12/18&15PK CAN CAR, RAMEN NOODLES...",Medium,Medium
2,3,2653.21,8540,921,219,"[GASOLINE-REG UNLEADED, SFT DRNK 2 LITER BTL C...",High,Medium
3,4,1200.11,382,301,110,"[PIZZA/ECONOMY, CHEESE CRACKERS (CHEEZ-ITS/GOL...",Medium,Low
4,5,779.06,245,222,125,"[ISOTONIC DRINKS SINGLE SERVE, ISOTONIC DRINKS...",Low,Low

In [36]:
household_txn_agg.shape

(2500, 8)

In [37]:
household_txn_agg.iloc[0]["SUB_COMMODITY_DESC"]

['ORANGES NAVELS ALL',
 'FRUIT/BREAKFAST BREAD',
 'BEANS GREEN: FS/WHL/CUT',
 'PUDDINGS DRY',
 'ENTREES']

In [38]:
sub_commodity_purchases.head()

   household_key   SUB_COMMODITY_DESC  total_quantity  total_sales
0              1     ADULT ANALGESICS               3        16.67
1              1         ADULT CEREAL               2         7.48
2              1     AEROSOL TOPPINGS               1         1.99
3              1  AIR CARE - AEROSOLS               1         2.99
4              1   AIR CARE - CANDLES               6        16.73

In [39]:
sub_commodity_purchase_segment = (
    sub_commodity_purchases
    .merge(
        segmented_data,
        on="household_key",
        how="left"
    )
)

sub_commodity_purchase_segment.head()

   household_key   SUB_COMMODITY_DESC  total_quantity  total_sales  cluster
0              1     ADULT ANALGESICS               3        16.67        1
1              1         ADULT CEREAL               2         7.48        1
2              1     AEROSOL TOPPINGS               1         1.99        1
3              1  AIR CARE - AEROSOLS               1         2.99        1
4              1   AIR CARE - CANDLES               6        16.73        1

In [40]:
sub_commodity_purchase_segment.shape

(610053, 5)

In [41]:
sub_commodity_purchase_segment["cluster"].value_counts()

cluster
1    422624
0    175989
2     11440
Name: count, dtype: int64

In [42]:
segment_sub_commodity_sales_agg = (
    sub_commodity_purchase_segment
    .groupby(
        [
            "cluster",
            "SUB_COMMODITY_DESC"
        ]
    )
    .agg(
        total_sales=("total_sales", "sum"),
        total_quantity=("total_quantity", "sum"),
        households=("household_key", "nunique")
    )
    .reset_index()
)

In [43]:
segment_sub_commodity_sales_agg.head()

   cluster SUB_COMMODITY_DESC  total_sales  total_quantity  households
0        0          ABRASIVES       497.68             303         146
1        0   ACNE MEDICATIONS      1137.55             208          87
2        0           ACTIVITY       304.60              82          50
3        0   ADDITIVES/FLUIDS       222.12              62          39
4        0    ADHESIVES/CAULK       215.33              97          60

In [44]:
segment_sub_commodity_sales_agg = (
    segment_sub_commodity_sales_agg
    .sort_values(
        [
            "cluster",
            "total_quantity",
            "total_sales"
        ],
        ascending=[True, False, False]
    )
)

In [45]:
segment_sub_commodity_sales_agg.head()

,cluster,SUB_COMMODITY_DESC,total_sales,total_quantity,households
648,0,GASOLINE-REG UNLEADED,470935.55,192835466,394
557,0,FLUID MILK WHITE ONLY,65961.87,37068,415
1676,0,YOGURT NOT MULTI-PACKS,14201.16,24142,357
1439,0,SOFT DRINKS 12/18&15PK CAN CAR,61788.07,21570,403
229,0,CANDY BARS (SINGLES)(INCLUDING,7795.00,20103,395

In [46]:
segment_top15 = (
    segment_sub_commodity_sales_agg
    .groupby("cluster")
    .head(15)
)

In [47]:
segment_top15.head(30)

,cluster,SUB_COMMODITY_DESC,total_sales,total_quantity,households
648,0,GASOLINE-REG UNLEADED,470935.55,192835466,394
557,0,FLUID MILK WHITE ONLY,65961.87,37068,415
1676,0,YOGURT NOT MULTI-PACKS,14201.16,24142,357
1439,0,SOFT DRINKS 12/18&15PK CAN CAR,61788.07,21570,403
229,0,CANDY BARS (SINGLES)(INCLUDING,7795.00,20103,395
1390,0,SFT DRNK 2 LITER BTL CARB INCL,19763.83,19643,387
1402,0,SHREDDED CHEESE,26586.34,13543,406
341,0,CONDENSED SOUP,13392.51,12967,395
113,0,BANANAS,12263.91,12506,409
861,0,MAINSTREAM WHITE BREAD,16128.70,12329,366
1482,0,SS ECONOMY ENTREES/DINNERS ALL,9176.90,9194,274
1173,0,POTATO CHIPS,20193.53,9107,407
1194,0,PREMIUM,27651.81,8809,403
1438,0,SOFT DRINK POWDER POUCHES,4115.71,8415,273
138,0,BEERALEMALT LIQUORS,60915.88,8210,342
2325,1,GASOLINE-REG UNLEADED,160759.58,63557738,1000
2234,1,FLUID MILK WHITE ONLY,94687.94,53704,1822
3353,1,YOGURT NOT MULTI-PACKS,24041.49,41682,1180
3067,1,SFT DRNK 2 LITER BTL CARB INCL,33515.04,34454,1510
3116,1,SOFT DRINKS 12/18&15PK CAN CAR,94732.00,32895,1563
1906,1,CANDY BARS (SINGLES)(INCLUDING,9838.12,25752,1447
3159,1,SS ECONOMY ENTREES/DINNERS ALL,21861.47,22220,998
2538,1,MAINSTREAM WHITE BREAD,27833.86,22057,1502
3079,1,SHREDDED CHEESE,40685.35,21501,1552
3115,1,SOFT DRINK POWDER POUCHES,7021.85,20675,826
2018,1,CONDENSED SOUP,19897.21,19778,1352
1790,1,BANANAS,17903.81,18878,1608
2850,1,POTATO CHIPS,32426.11,14916,1559
2774,1,PASTA: CANNED,13538.54,13742,914
2925,1,RAMEN NOODLES/RAMEN CUPS,4448.11,13528,836

In [48]:
segment_popular_items = (
    segment_top15
    .groupby("cluster")
    ["SUB_COMMODITY_DESC"]
    .apply(list)
    .reset_index()
)

segment_popular_items.head()

   cluster                                 SUB_COMMODITY_DESC
0        0  [GASOLINE-REG UNLEADED, FLUID MILK WHITE ONLY,...
1        1  [GASOLINE-REG UNLEADED, FLUID MILK WHITE ONLY,...
2        2  [GASOLINE-REG UNLEADED, FLUID MILK WHITE ONLY,...

In [49]:
segment_scores = (
    segment_sub_commodity_sales_agg
    .copy()
)

segment_scores["segment_score"] = (
    segment_scores
    .groupby("cluster")["total_quantity"]
    .transform(
        lambda x:
        x / x.max()
    )
)

In [50]:
segment_popular_items

   cluster                                 SUB_COMMODITY_DESC
0        0  [GASOLINE-REG UNLEADED, FLUID MILK WHITE ONLY,...
1        1  [GASOLINE-REG UNLEADED, FLUID MILK WHITE ONLY,...
2        2  [GASOLINE-REG UNLEADED, FLUID MILK WHITE ONLY,...

In [51]:
segment_popular_items['SUB_COMMODITY_DESC'][0]

['GASOLINE-REG UNLEADED',
 'FLUID MILK WHITE ONLY',
 'YOGURT NOT MULTI-PACKS',
 'SOFT DRINKS 12/18&15PK CAN CAR',
 'CANDY BARS (SINGLES)(INCLUDING',
 'SFT DRNK 2 LITER BTL CARB INCL',
 'SHREDDED CHEESE',
 'CONDENSED SOUP',
 'BANANAS',
 'MAINSTREAM WHITE BREAD',
 'SS ECONOMY ENTREES/DINNERS ALL',
 'POTATO CHIPS',
 'PREMIUM',
 'SOFT DRINK POWDER POUCHES',
 'BEERALEMALT LIQUORS']

In [52]:
segment_scores.head(20)

,cluster,SUB_COMMODITY_DESC,total_sales,total_quantity,households,segment_score
648,0,GASOLINE-REG UNLEADED,470935.55,192835466,394,1.000000
557,0,FLUID MILK WHITE ONLY,65961.87,37068,415,0.000192
1676,0,YOGURT NOT MULTI-PACKS,14201.16,24142,357,0.000125
1439,0,SOFT DRINKS 12/18&15PK CAN CAR,61788.07,21570,403,0.000112
229,0,CANDY BARS (SINGLES)(INCLUDING,7795.00,20103,395,0.000104
1390,0,SFT DRNK 2 LITER BTL CARB INCL,19763.83,19643,387,0.000102
1402,0,SHREDDED CHEESE,26586.34,13543,406,0.000070
341,0,CONDENSED SOUP,13392.51,12967,395,0.000067
113,0,BANANAS,12263.91,12506,409,0.000065
861,0,MAINSTREAM WHITE BREAD,16128.70,12329,366,0.000064
1482,0,SS ECONOMY ENTREES/DINNERS ALL,9176.90,9194,274,0.000048
1173,0,POTATO CHIPS,20193.53,9107,407,0.000047
1194,0,PREMIUM,27651.81,8809,403,0.000046
1438,0,SOFT DRINK POWDER POUCHES,4115.71,8415,273,0.000044
138,0,BEERALEMALT LIQUORS,60915.88,8210,342,0.000043
604,0,FRZN BAGGED VEGETABLES - PLAIN,10174.46,8040,340,0.000042
317,0,CIGARETTES,48685.77,7936,223,0.000041
1393,0,SFT DRNK SNGL SRV BTL CARB (EX,7994.44,7679,319,0.000040
634,0,FRZN SS PREMIUM ENTREES/DNRS/N,16559.73,7660,256,0.000040
405,0,DAIRY CASE 100% PURE JUICE - O,18984.23,7641,391,0.000040

In [53]:
#creating a collaborative matrix per house
#segment recommendation and household recommendation

1. Collabaritive matrix for our households
2. Find the similarity of the households
3. Caller function to get similar household for a particular households.
4. Get the products.

In [54]:
sub_commodity_purchases.head()

   household_key   SUB_COMMODITY_DESC  total_quantity  total_sales
0              1     ADULT ANALGESICS               3        16.67
1              1         ADULT CEREAL               2         7.48
2              1     AEROSOL TOPPINGS               1         1.99
3              1  AIR CARE - AEROSOLS               1         2.99
4              1   AIR CARE - CANDLES               6        16.73

In [55]:
sub_commodity_purchases["SUB_COMMODITY_DESC"].nunique()

1677

In [56]:
sub_commodity_purchases['SUB_COMMODITY_DESC'].value_counts()

SUB_COMMODITY_DESC
FLUID MILK WHITE ONLY             2392
BANANAS                           2105
SOFT DRINKS 12/18&15PK CAN CAR    2059
POTATO CHIPS                      2046
SHREDDED CHEESE                   2031
PREMIUM                           1984
SFT DRNK 2 LITER BTL CARB INCL    1976
MAINSTREAM WHITE BREAD            1960
EGGS - LARGE                      1937
CANDY BARS (SINGLES)(INCLUDING    1909
TORTILLA/NACHO CHIPS              1882
POURABLE SALAD DRESSINGS          1864
DAIRY CASE 100% PURE JUICE - O    1858
TOILET TISSUE                     1830
CONDENSED SOUP                    1802
SEMI-SOLID SALAD DRESSING MAY     1780
SUGAR                             1775
PRIMAL                            1775
IWS SINGLE CHEESE                 1773
SPICES & SEASONINGS               1773
HAMBURGER BUNS                    1743
MARGARINE: TUBS AND BOWLS         1740
POTATOES RUSSET (BULK&BAG)        1715
ALL FAMILY CEREAL                 1708
EGGS - X-LARGE                    1682
KIDS CEREAL                       1680
MAINSTREAM WHEAT/MULTIGRAIN BR    1680
HOT DOG BUNS                      1642
CREAM CHEESE                      1638
BEERALEMALT LIQUORS               1628
CHOICE BEEF                       1623
SOUR CREAMS                       1607
CATSUP                            1605
PEANUT BUTTER                     1597
PAPER TOWELS & HOLDERS            1595
YOGURT NOT MULTI-PACKS            1582
MAINSTREAM                        1579
SPAGHETTI DRY                     1563
SNACK CAKE - MULTI PACK           1559
SNACKS/APPETIZERS                 1530
LIQUID LAUNDRY DETERGENTS         1510
CHEWING GUM                       1497
SFT DRNK SNGL SRV BTL CARB (EX    1494
LEAN                              1489
NOODLES DRY                       1466
SOUP CRACKERS (SALTINE/OYSTER)    1462
ADULT CEREAL                      1460
STRAWBERRIES                      1460
SMOKED/COOKED                     1459
FRZN BAGGED VEGETABLES - PLAIN    1458
CHEESE CRACKERS (CHEEZ-ITS/GOL    1445
TUNA                              1444
GASOLINE-REG UNLEADED             1438
CORN                              1438
MACARONI & CHEESE DNRS            1427
SWEET GOODS - FULL SIZE           1422
MEXICAN SAUCESSALSAPICANTEE       1419
NON-CRBNTD DRNKING/MNERAL WATE    1417
SW GDS:DONUTS                     1417
HEAD LETTUCE                      1402
PRETZELS                          1399
BEANS GREEN: FS/WHL/CUT           1386
RTS SOUP: CHUNKY/HOMESTYLE ET     1383
BUTTER SPRAY CRACKER (RITZ/CLU    1380
POULTRY                           1363
CARROTS MINI PEELED               1358
CHICKEN BREAST BONELESS           1358
ENHANCED                          1358
ONIONS SWEET (BULK&BAG)           1347
FRZN BREADED PREPARED CHICK       1342
CARDS EVERYDAY                    1327
NATURAL CHEESE EXACT WT CHUNKS    1318
GRAPES RED                        1317
FRZN GARLIC BREAD/TOAST/STICKS    1311
SS ECONOMY ENTREES/DINNERS ALL    1311
BBQ SAUCE                         1307
HAM                               1307
PICKLES                           1306
PREPARED BEANS - BAKED W/PORK     1297
TOOTHPASTE                        1297
VARIETY BEANS - KIDNEY PINTO      1295
CANDY BARS (MULTI PACK)           1295
COTTAGE CHEESE                    1294
TRADITIONAL                       1287
GRAPES WHITE                      1277
CELERY                            1277
MOLASSES & SYRUPS                 1275
FRZN MULTI SERVE ENTREES ALL      1264
PEPPERS GREEN BELL                1257
FRZN FRENCH FRIES                 1255
MEAT: TURKEY BULK                 1255
LIQUID DISH DETERGENT             1254
CANDY BAGS-CHOCOCLATE             1252
REGULAR GARDEN                    1251
REFRIGERATED BISCUITS REGULAR     1244
PREMIUM - MEAT                    1239
PASTA: CANNED                     1238
BOLOGNA                           1226
SANDWICH COOKIES                  1225
RICE SIDE DISH MIXES DRY          1221
MACARONI DRY                      1198
FRZN SS PREMIUM ENTREES/DNRS/T    1197
SPRING WATER                      1196
STICKS/ENROBED                    1196
SFT DRNK MLT-PK BTL CARB (EXCP    1194
SHAMPOO                           1192
TOMATOES: STEWED/DICED/CRMD       1188
TOMATOES VINE RIPE BULK           1182
TRAY PACK/CHOC CHIP COOKIES       1177
SALAD MUSTARD                     1177
CHOCOLATE MILK                    1175
LAYER CAKE MIX                    1173
VEGETABLE/SALAD OIL               1173
SNACK CRACKERS                    1166
POPCORN - MICROWAVE               1160
CANISTER POTATO/TORT CHIPS        1157
ORANGES NAVELS ALL                1155
CUCUMBERS                         1155
MEAT:HAM BULK                     1153
ALUMINUM FOIL                     1153
SEASONAL CANDY BAGS-CHOCOLATE     1139
WAFFLES/PANCAKES/FRENCH TOAST     1138
CANDY BAGS-NON CHOCOLATE          1130
SALAD BAR FRESH FRUIT             1130
SOFT DRINK POWDER POUCHES         1124
ADULT ANALGESICS                  1122
PIZZA/PREMIUM                     1121
SANDWICHES&HANDHELDS              1115
FRUIT BOWL AND CUPS               1112
FROSTING                          1109
PEPPERONI/SALAMI                  1109
TOASTER PASTRIES                  1106
SOFT DRINKS 20PK&24PK CAN CARB    1106
PINEAPPLE                         1105
DAIRY CASE JUICE DRNK UNDER 10    1105
EGGS - MEDIUM                     1102
TOMATOES HOTHOUSE ON THE VINE     1102
RAMEN NOODLES/RAMEN CUPS          1098
ECONOMY                           1093
YOGURT MULTI-PACKS                1088
FRZN WHIPPED TOPPING              1085
SAUCE MIXES GRAVY MIXES DRY       1077
BAGGED CHEESE SNACKS              1072
MARGARINE  STICK                  1071
ROLLS - PORK                      1066
GARDEN PLUS                       1065
REFRIGERATED SPECILATY ROLLS      1064
GROUND COFFEE                     1061
FACIAL TISSUE & PAPER HANDKE      1047
BLENDS                            1046
ASEPTIC PACK JUICE AND DRINKS     1044
INSTORE CUT FRUIT                 1034
CHILI: CANNED                     1032
MISCELLANEOUS CANDY (INCLUDING    1032
WATER ICE                         1031
FLOUR: WHITE & SELF RISING        1028
CHEESE: NATURAL BULK              1021
PIZZA/TRADITIONAL                 1018
COOKIES: REGULAR                  1013
POTATOES: DRY                     1011
MUFFIN & CORN BREAD MIX           1007
ONIONS WHITE (BULK&BAG)           1004
CORN CHIPS                        1004
ISOTONIC DRINKS SINGLE SERVE      1002
INSTANT OATMEAL                   1002
CIGARETTES                         998
PRESERVES JAM MARMALADE            997
GARBAGE KITCHEN COMPACTOR BA       996
MEXICAN SEASONING MIXES            991
DIPS (NON-REFRIGERATED)            991
LIQUID BLEACH                      987
BUTTER                             983
MISCELLANEOUS                      983
CHICKEN BREAST BONE IN             983
STUFFING MIXES                     982
SELECT BEEF                        978
SKILLET DINNERS                    975
REFRIG DIPS                        972
FRZN SS PREMIUM ENTREES/DNRS/N     967
ONIONS YELLOW (BULK&BAG)           963
JELLY                              963
SGL SV/VEND MACH SNACKS CHIP/P     962
PIZZA/ECONOMY                      959
BREAD:ITALIAN/FRENCH               957
APPLES RED DELICIOUS (BULK&BAG     953
ALKALINE BATTERIES                 951
TOMATO SAUCE                       947
STEAK & WORCHESTER SAUCE           946
BROTH                              939
GADGETS/TOOLS                      937
BAR SOAP                           935
GRANOLA BARS                       929
GRATED CHEESE                      920
ONIONS OTHER                       916
REFRIGERATED PUDDING               908
BREAST - BONELESS(IQF)             908
PLSTC CTLRYTBLCLTHSTTHPKSST        907
MISC SALES TRANS                   903
ECONOMY - MEAT                     899
VANILLA WAFER/KIDS COOKIES         897
MALTED MLK/SYRUP/PWDRS (EGGNOG     893
FRUIT SNACKS                       891
CANTALOUPE WHOLE                   889
NO SUBCOMMODITY DESCRIPTION        884
PAPER NAPKINS                      883
BETTER FOR YOU                     876
BROCCOLI WHOLE&CROWNS              874
NOODLE SIDE DISH MIXES             872
ICE - CRUSHED/CUBED                871
STRING CHEESE                      869
REFRIGERATED COOKIES-CHUB          865
FRZN BOXED VEGETABLES- VALUE A     864
ENTREES                            862
PEACHES YELLOW FLESH               862
BAGELS                             861
APPLES GALA (BULK&BAG)             859
FEM. HYGN.NAPKINS                  858
GRND/PATTY - FROZEN                855
SOLID/STK DEODORANTS               853
HAIR CONDITIONERS AND RINSES       849
NATURAL CHEESE EXACT WT SLICES     847
MARSHMALLOWS                       846
APPLE JUICE & CIDER (OVER 50%      846
PREMIUM PINTS                      846
PEAS GREEN                         843
BROWNIE MIX                        840
MINTS CANDY & BREATH (NOT LIF      837
CONES                              834
ICE CREAM SANDWICHES               834
CARDS SEASONAL                     830
CROUTONS SALAD TOPPERS BREAD       828
CEREAL BARS                        827
COOKING SPRAYS                     825
RAZORS AND BLADES                  818
PREMIUM BREAD                      816
LINKS - RAW                        814
REFRIGERATED MEXICAN PRODUCTS      813
VAC PAC NUTS(CANS)                 808
DISPOSABLE FOILWARE                805
NEWSPAPER                          804
PUDDING&GELATIN CUPS/CANS          803
APPLES OTHER (BULK&BAG)            802
FRZN BRD STICK/PORTON              799
LUNCH COMBO                        789
SANDWICH BAGS                      788
PUDDINGS DRY                       788
HOT SAUCE                          784
SOFT DRINKS 6PK/4PK CAN CARB (     783
LEMONS                             782
DRY SOUP                           779
GRAVY CAN/GLASS                    779
MEXICAN SOFT TORTILLAS AND WRA     779
POTATOES RED (BULK&BAG)            779
MISCELLANEOUS CHEESE               778
VEGETABLE SALADS - PREPACK         778
PATTIES                            777
FRZN BREAKFAST ENTREES/SANDWIC     776
INSIDE FROST BULBS                 774
RICE - INSTANT & MICROWAVE         771
SOFT DRINK BOTTLE NON-CARB (EX     760
CABBAGE                            759
PEACHES                            754
SANDWICH BUNS                      753
TOMATOES GRAPE                     750
BODY WASH                          748
ORAL HYGIENE BRUSHES               748
BREADINGS  COATINGS CRUMBS         745
LOAF CHEESE                        743
TABLE SALT POPCORN SALTICE C       742
RIBS                               740
GRAHAM CRACKERS                    736
FRESH                              735
ANTI-ACIDS                         734
LIQUID SOAP                        733
PANCAKE MIXES                      733
REFRIGERATED COFFEE CREAMERS       732
MISCELLANEOUS MILK                 729
CORN YELLOW                        729
APPLES GRANNY SMITH (BULK&BAG)     729
SEASONAL MISCELLANEOUS             726
BITS & MORSELS                     726
APPLES GOLD DELICIOUS (BULK&BA     723
FABRIC SOFTENER SHEETS             723
TEA BAGS & BULK TEA                717
MULTI-PACK CRACKERS                715
VINEGAR ALL-EXCEPT WINE/RIC        714
HOT CHOCOLATE COCOA MIX            711
MELON HALVES/QUARTERS              708
ANGUS                              708
MISC BAG SNACKS                    707
SPECIALTY COOKIES                  698
MEAT: SAUS DRY BULK                697
VARIETY LETTUCE                    697
ANTIPERSPIRANTS ONLY (ALL OTHE     696
RELISHES                           696
ROLLS: DINNER                      696
FREEZER BAGS                       687
COUGH SYRP/LOZNG-DRP/XPCTRNT       686
POTATOES SWEET&YAMS                685
BAKING NUTS                        677
CHICKEN DRUMS                      673
COLD AND FLU - DXM                 673
FRZN BOXED VEGETABLES - PLAIN      669
NATURAL BEEF                       668
CHIX: ROTISSERIE (HOT)             667
COLD AND FLU                       667
ROMA TOMATOES (BULK/PKG)           664
PREP FD: SIDE DISHES (HOT)         664
SW GDS: SW ROLLS/DAN               664
FOAM PLATES                        663
FOOD STORAGE BAGS                  663
NON DAIRY CREAMER: DRY             659
PEPPERS RED BELL                   658
FRUIT COCKTAIL FRUIT SALAD         658
RAISINS                            657
MEAT: LUNCHMEAT BULK               656
FEM. HYGN. TAMPONS                 656
PIES: FRUIT/NUT                    655
PLASTIC CUPS                       655
GELATIN                            654
DIPS                               653
WATERMELON SEEDLESS WHOLE          650
MUSHROOMS CND & GLASS              649
NON-CARB FLVRD DRNKNG/MNRL WAT     648
COFFEE FILTERS                     648
MEAT SUPPLIES                      647
CAKES: LAYERS                      646
CANNED MILK                        644
LOIN - CHOPS BONELESS              644
TOMATO PASTE                       641
ENGLISH MUFFINS/WAFFLES            639
MEAT: BEEF BULK                    638
APPLE SAUCE                        634
STANDARD OATMEAL                   633
SUPER PREMIUM PINTS                632
BABY DIAPERS                       632
WHOLE CHICKEN (ROASTERS/FRYER)     631
PLUMS                              631
FRZN BAGGED VEGETABLES- VALUE      630
CARROTS BAGGED                     628
MEXICAN DINNERS AND FOODS          626
PREMIUM - BEEF                     625
FRZN TATER TOTS/OTHER EXTRUDED     621
PREMIUM COOKIES (EX: PEPPERIDG     620
CAKES: NOVELTIES                   618
FABRIC SOFTENER LIQUID             617
RICE - DRY BAG AND BOX             616
CHEESE: PROCESSED BULK             614
SANDWICH SAUCE                     613
MANDARIN ORANGES/CITRUS SECT       612
BAGGED POPPED POPCORN              611
ONIONS RED (BULK&BAG)              611
DINNER ROLLS                       608
MOUTHWASH RINSES AND SPRAYS        606
CHOCOLATE COVERED COOKIES          605
AEROSOL TOPPINGS                   604
MEXICAN TACO TOSTADO SHELLS        602
HOT MUSTARD/SPECIALTY MUSTAR       600
OLIVE OIL                          595
TAPE & MAILING PRODUCTS            595
SEAFOOD-FRZ-IQF RAW SHRIMP RW      590
BLENDED JUICE&COMBINATIONS (OV     588
SOFT DRINKS CAN NON-CARB (EXCE     587
SNACK MIX                          585
CRANBERRY JUICE (50% AND UNDER     583
ASPARAGUS                          582
FRZN HASHBROWN POTATOES            578
SHAVE CREAMS AND POWDERS           577
MISC MEAT SAUCES                   577
PLASTIC TRASH BAGS                 575
SOUP/STEW                          574
DRY BEANS/PEAS/BARLEY: BAG & B     574
TEA SWEETENED                      573
SEASONAL CANDY BAGS NON-CHOCOL     572
CRANAPPLE CRAN GRAPE JUICE (5      571
CANOLA OILS                        566
GRAPE JUICE (OVER 50% JUICE)       563
MEXICAN BEANS REFRIED              562
SINUS AND ALLERGY                  560
BABY WIPES                         560
BLENDED JUICE&COMBINATIONS (50     558
JUICE (UNDER 10% JUICE)            557
SEAFOOD-FRZ-RAW FILLETS            556
ICE CREAM TOPPINGS                 555
AIR CARE - CONTINUOUS ACTION       554
BLUEBERRIES                        553
HAIR SETS AND GELS                 550
DISPOSABLE FD STORAGE CONTAINR     549
BAKING POWDER & SODA               548
ROLLS: SANDWICH                    546
TOMATOES VINE RIPE PKG             542
VEG JUICE (EXCEPT TOMATO) (OVE     541
LIPCARE                            540
DAIRY CASE 100% PURE JUICE OTH     540
SWEETENERS                         538
SPONGES: BATH HOUSEHOLD            536
CORN DOGS                          536
VEGETABLES ALL OTHER               536
PANTRY                             535
GREEN OLIVES                       534
GARLIC WHOLE CLOVES                534
BASIC PAPER PLATES                 534
DAIRY CASE CITRUS PNCH/OJ SUBS     531
PEARS                              531
REFRIGERATED COOKIES-BREAK N B     529
CAKE DECORS & ICING                529
LIMES                              529
ISOTONIC DRINKS MULTI-SERVE        527
RYE BREADS                         522
PLASTIC/HEAVY PAPER PREM PLATE     521
SOFT DRINK CANISTERS               519
MISCELLANEOUS PACKAGE MIXES        518
GUM (PACKAGED)                     515
RIPE OLIVES                        513
MUSHROOMS W/WHOLE PKG              512
FRUIT DRINKS: CANNED & GLASS (     511
POTATOES OTHER                     510
VARIETY PACK                       509
HONEY                              508
WRITING INSTRUMENTS                508
CHICKEN THIGHS                     507
NECTARINES YELLOW FLESH            506
DRIED FRUIT - OTHER                505
DRY CAT FOOD (CAT CHOW/FRISKIE     504
CRANBERRY SAUCE                    503
AIR CARE - AEROSOLS                503
BREAD:SAVORY/SPECIALTY             502
CLEANING WIPES                     502
FROZEN FRUIT PIES  & COBBLERS      501
MUSHROOMS WHITE SLICED PKG         500
BATHROOM CLEANERS - GENERAL        500
MISCELLANEOUS VEGETABLES           497
WOMEN S GENERAL-MAGAZINE           494
CAULIFLOWER WHOLE                  493
COOKIES: HOLIDAY/SPECIAL OCCAS     493
PIE FILLING MINCEMEAT GLAZES       493
HAND AND BODY LOTIONS              492
TEA BAGS HERBAL & FLAVORED         492
PICKLD VEG PEPPERS ETC             488
CHIX:FRD 8PC/CUT UP (HOT)          485
MULTI-PACK COOKIES                 485
SCHOOL PAPER                       484
WINGS (IQF)                        484
BANDAGE/TAPE                       484
DIET/LIGHT BREAD                   482
BURRITOS                           481
PRODUCE DEPT KEY RING              481
MISCELLANEOUS H & B AIDS           480
CHARCOAL                           480
MISC REFRIG DOUGH PRODUCTS         478
DRESSINGS                          476
SPINACH & GREENS                   476
GIFT-WRAP EVERYDAY                 472
CHERRIES RED                       472
REFRIGERATED BAGELS                471
DAIRY CASE FRUIT DRINKS (NO JU     468
COVERGIRL                          467
CHEESE:SPECIALTY PREPACK           466
BISCUIT FLOUR & MIXES              466
DRY                                465
VALUE                              461
TV/MOVIE-MAGAZINE                  459
LAXATIVES                          459
ENERGY DRINK                       459
POTATOES SWEET                     457
GRAPEFRUIT                         456
SOIL & STAIN REMOVER               456
SNACK NUT(BAG)                     455
SANDWICH SAUCE HORSERADISH SA      455
CANDY BARS MULTI PACK W/FLOUR      454
PATTIES - RAW                      453
SALAD SPINACH                      452
BEANS                              451
ORIENTAL OTHER SAUCES MARINAD      450
KOSHER/SPECIALTY                   449
PLASTIC WRAP (SARANETC.)           448
FRZN BREAKFAST PASTRY              447
PORK-FULLY COOKED                  447
DESIGNER PAPER: MEDIUM WEIGHT      447
CHEESE: NATURAL PREPORTND          446
SAUERKRAUT                         445
SCOURING PADS & CLOTH              445
DRY DOG FOOD PREMIUM (ALPO/PUR     442
COUPONS/STORE & MFG                442
BABY FOOD - BEGINNER               439
FRZN BURGERS/BBQ/MEATBALL          437
METAL BAKEWARE                     435
SAL:SALSA/DPS-PRPCK                434
MAYBELLINE                         434
ROLLS - FLAVORED/OTHER             433
CUT VEGETABLES ALL OTHER           433
TOILET BOWL MANUAL                 432
SEAFOOD-FRE-NON RW-ALL             431
SANDWICHES/BISCUITS/GRAVY          431
LINAMENTS                          430
GRAPES BLACK/BLUE                  429
MISC SNACKS                        428
SOLID SHORTENING                   427
HOT DOG CHILI SAUCE                427
AUTO DISH DETERGENT - GEL          425
PIZZA SAUCE                        425
SW GDS:COFFEE CAKES                424
CUPS/PUSH UPS/OTHER                423
SQUASH ZUCCHINI                    422
FACIAL SOAPS-SCRUBS-MASKS          422
FLAVORED/OTHER                     420
ORGANIC CARROTS                    420
ORIENTAL SOY SAUCE                 417
PAILS                              416
RICE CAKES                         416
FROZEN FRUIT                       415
PIZZA/SINGLE SERVE/MICROWAVE       413

In [57]:
household_item_matrix = sub_commodity_purchases.pivot_table(index = 'household_key', columns = 'SUB_COMMODITY_DESC', values = 'total_quantity').fillna(0)

In [58]:
household_item_matrix.head()

SUB_COMMODITY_DESC,ABRASIVES,ACNE MEDICATIONS,ACTIVITY,ADDITIVES/FLUIDS,ADHESIVES/CAULK,ADULT ANALGESICS,ADULT CEREAL,ADULT INCONTINENCE BRIEFS,ADULT INCONTINENCE MISC PRODUC,ADULT INCONTINENCE PADS,ADULT INCONTINENCE UNDERGARMEN,ADULT PREMIUM,AEROSOL DEODORANTS,AEROSOL TOPPINGS,AGE RESTRICTED DVD S,AGE RESTRICTED FIREWORKS,AGE RESTRICTED SPHE $9.99,AIR CARE - AEROSOLS,AIR CARE - CANDLES,AIR CARE - CONTINUOUS - NON EL,AIR CARE - CONTINUOUS ACTION,AIR CARE - DISINFECTANT SPRAYS,AIR CARE - RUG,AIR CARE - SANITIZERS,ALKALINE BATTERIES,ALL CAMPING ACCESSORIES,ALL FABRIC DRY BLEACH,ALL FABRIC LIQUID BLEACH,ALL FAMILY CEREAL,ALL OTHER IMPORTED WINES,ALL UNDERWEAR,ALMAY,ALMONDS SHELLED,ALTERNATIVE LITTER,ALUMINUM FOIL,AMMONIA,ANGUS,ANGUS BEEF,ANT AND ROACH,ANTI-ACIDS,ANTIFREEZE,ANTIPERSPIRANTS ONLY (AEROSOL),ANTIPERSPIRANTS ONLY (ALL OTHE,APPLE BUTTER,APPLE JUICE & CIDER (50% AND U,APPLE JUICE & CIDER (OVER 50%,APPLE SAUCE,APPLES BRAEBURN (BULK&BAG),APPLES FUJI (BULK&BAG),APPLES GALA (BULK&BAG),APPLES GOLD DELICIOUS (BULK&BA,APPLES GRANNY SMITH (BULK&BAG),APPLES OTHER (BULK&BAG),APPLES RED DELICIOUS (BULK&BAG,APPLES WEDGE/SLICES,APPLICATORS,APRICOTS,AQUARIUM NEEDS,AREA REPELLANTS,AREA RUGS,ART SUPPLIES,ARTIFICIAL TREES,AS SEEN ON TV,ASCEPTIC,ASEPTIC MILK & MILK DRINKS,ASEPTIC PACK JUICE AND DRINKS,ASPARAGUS,ATHLETIC GIFT ITEMS,AUSTRALIAN/NZ WINES,AUTHENTIC INDIAN FOODS,AUTHENTIC JAPANESE FOODS,AUTHENTIC PASTA RICE BEANS,AUTHENTIC PEPPERS,AUTHENTIC SAUCES SALSA PICAN,AUTHENTIC SOUPS BOUILLONS,AUTHENTIC THAI FOODS,AUTHENTIC VEGETABLES AND FOODS,AUTO DISH DETERGENT - GEL,AUTO DISH DETERGENT - MONODOSE,AUTOMATIC DISHWASHER DETERGENT,AUTOMOBILE-MAGAZINE,AVOCADO,BABY ANTIBIOTIC OINTMENTS & CR,BABY BASIC INFANT ACC TOYS,BABY BASICS,BABY CEREAL,BABY CRACKERS,BABY CREAMS & OINTMENTS,BABY DIAPERS,BABY FOOD,BABY FOOD - BEGINNER,BABY FOOD CEREALS,BABY FOOD JUNIOR ALL BRANDS,BABY ISOTONIC DRINKS,BABY JUICES,BABY LOTIONS & OILS,BABY POWDERS,BABY SOAPS,BABY SPRING WATERS,BABY TOYS,BABY WIPES,BACON - BELLY/JOWL,BAGELS,BAGGED CHEESE SNACKS,BAGGED POPPED POPCORN,BAGS/TAGS/TISSUE/BOXES,BAKING COCOA,BAKING CUPS,BAKING NUTS,BAKING POWDER & SODA,BALLOONS 18IN PKG LICENSED,BALLOONS 18IN PKG NON LICENSED,BALLOONS SHAPES/OTHER,BANANAS,BANDAGE/TAPE,BANDANA/SCARVES,BAR SOAP,BARBIE,BARGAIN,BARS - GRANOLA/SNACK,BASIC CALC,BASIC OPENSTOCK,BASIC PAPER PLATES,BATH ACCESSORIES,BATH BUBBLES-BATH SOAPS-ADDITI,BATH SPONGES/ACCESSORIES,BATHROOM CLEANERS - GENERAL,BATHROOM CLEANERS - SPECIALTY,BATTERIES,BBQ SAUCE,BEANS,BEANS GREEN: FS/WHL/CUT,BEANS WAX SHELLIES,BEDDING ACCESSORIES,BEEF - FULLY COOKED,BEEF STEW,BEEF/PORK - DRIED SLICED W/GRA,BEERALE -NON ALCOHOLIC,BEERALEMALT LIQUORS,BEETS,BETTER FOR YOU,BEVERAGE WINES,BINDERS & PORTFOLIOS,BISCUIT FLOUR & MIXES,BITS & MORSELS,BLACKBERRIES,BLEND/MIX,BLENDED JUICE&COMBINATIONS (50,BLENDED JUICE&COMBINATIONS (OV,BLENDS,BLUEBERRIES,BOBBY PINS AND ACCESSORIES,BODY WASH,BOLOGNA,BONNE BELL,BOUILLON,BOUQUET (NON ROSE) ALL OTYHER,BOUQUET EVERYDAY MUSICAL,BOURBON/TN WHISKEY,BOX WINES,BOXED CHRISTMAS CARDS,BOXED GLASSWARE,BOXED ORNAMENTS,BOXED PREPARED/ENTREE/DRY PREP,BREAD:ITALIAN/FRENCH,BREAD:LOAF/SNACK,BREAD:PARTY BREADS,BREAD:PITA/POCKET BREADS,BREAD:SAVORY/SPECIALTY,BREAD:SWEET/BREAKFAST,BREAD:TORTILLAS/PITA,BREADED - CHICKEN,BREADINGS COATINGS CRUMBS,BREAKFAST BARS/TARTS/SCONES,BREAKFAST CRYSTALS,BREAST - BONELESS,BREAST - BONELESS(IQF),BRIDAL-MAGAZINE,BROCCOLI WHOLE&CROWNS,BROCCOLI/CAULIFLOWER PROCESSED,BROOMS: PLSTC/NATRL & PATIO,BROTH,BROTHS,BROWNIE MIX,BRUSHES,BUILDERS HARDWARE,BULK CANDY,BULK CANDY W/FLOUR,BULK PLASTICS,BUNCHES 2-4 STEM (OTHER),BURRITOS,BUSINESS&FINANCE-MAGAZINE,BUTTER,BUTTER SPRAY CRACKER (RITZ/CLU,BUTTERMILK,BUTTS,CABBAGE,CAKE DECORS & ICING,CAKE DECORS - BIRTHDAY CANDLES,CAKES - OTHER,CAKES: ANGEL FDS/CKE ROLLS,CAKES: BIRTHDAY/CELEBRATION SH,CAKES: CHEESECAKE,CAKES: CNDLES/RETL ACCSS,CAKES: CREME/PUDDING,CAKES: ICE CREAM,CAKES: LAYERS,CAKES: NOVELTIES,CAKES: SHEET,CAKES:BIRTHDAY/CELEBRATION LAY,CALENDAR,CALGON,CAMPING APPLIANCES,CAN CATFD GOURMET/SUP PREM (GR,CAN DOG FOOD (SKIPPY/PEDIGREE/,CAN DOG FOOD RATION (TRIX/VETS,CAN DOGFD GOURMET/SUPER PREM (,CAN/BTL BEVERAGE,CANDLES,CANDLES & LIGHTING,CANDLES ACCESSORIES,CANDLES SEASONAL,CANDY,CANDY & BREATH MINTS (PKGD) (N,CANDY BAGS-CHOCOCLATE,CANDY BAGS-CHOCOCLATE W/FLOUR,CANDY BAGS-NON CHOCOLATE,CANDY BAGS-NON CHOCOLATE W/FLO,CANDY BARS (MULTI PACK),CANDY BARS (SINGLES)(INCLUDING,CANDY BARS MULTI PACK W/FLOUR,CANDY BOX NON-CHOCOLATE,CANDY BOXED CHOCOLATES,CANDY BOXED CHOCOLATES W/FLOUR,CANDY REFRIGERATED,CANDY/CHOCOLATE,CANISTER POTATO/TORT CHIPS,CANNED CAT FOOD (9 LIVES/FRISK,CANNED CAT FOOD RATION (ECONOM,CANNED MILK,CANNING JARSLIDSUTENSILSMIS,CANNING SPICESSALSAPICKLING,CANOLA OILS,CANS SOUP/CHILI,CANTALOUPE WHOLE,CARAMEL COATED SNACKS,CARBONATED WATER - FLVRD SWEET,CARBONATED WATER - FLVRD UNSWE,CARBONATED WATER - UNFLAVORED,CARD GAMES,CARDS EVERYDAY,CARDS SEASONAL,CARNATIONS,CARPET CLEANERS,CARROTS,CARROTS - BULK,CARROTS BAGGED,CARROTS MINI PEELED,CARROTS SLICED/SHRED/STICKS,CAT TREATS,CATSUP,CAULIFLOWER WHOLE,CB (NON ROSE)LILY,CD-R,CELERY,CELERY CHOPPED/STICKS,CENTRAL AMERICAN FOODS,CEREAL - COLD,CEREAL - HOT,CEREAL BARS,CHARCOAL,CHARCOAL LIGHTER FLUID/UTILITY,CHEESE,CHEESE CRACKERS (CHEEZ-ITS/GOL,CHEESE: NATURAL BULK,CHEESE: NATURAL PREPORTND,CHEESE: PROCESSED BULK,CHEESE:CHEESEBALLS/SPREADS,CHEESE:PROCESSED PREPORTND,CHEESE:SPECIALTY BULK,CHEESE:SPECIALTY PREPACK,CHEMICALS,CHEMICALS/MTL POLISH/MOTH,CHERRIES (EXCEPT MARASCHINO),CHERRIES RANIER,CHERRIES RED,CHEWING GUM,CHICKEN BREAST BONE IN,CHICKEN BREAST BONELESS,CHICKEN DRUMS,CHICKEN LEGS/QUARTERS,CHICKEN THIGHS,CHICKEN WINGS,CHICKEN-FULLY COOKED,CHILDREN S ACTIVITY,CHILDREN-MAGAZINE,CHILDRENS LOW END,CHILI SAUCE COCKTAIL SAUCE,CHILI: CANNED,CHIX: BAKED 8PC CUT UP (HOT),CHIX: CHICKEN DINNERS/SNACKS H,CHIX: ROTISSERIE (HOT),CHIX: ROTISSERIE COLD,CHIX: VALUE ADDED (HOT),CHIX:FRD 8PC/CUT UP (COLD),CHIX:FRD 8PC/CUT UP (HOT),CHIX:VALUE ADDED (COLD),CHOCOLATE COVERED COOKIES,CHOCOLATE MILK,CHOCOLATE SYRUP,CHOICE BEEF,CHRISTMAS LIGHTS,CHUCK/SHLDR - STK/CHP/SLC,CHUCK/SHOULDER,CHUNK MEATS - ALL,CIDER,CIG LIGHTERS/LTR FLUID/PIPES,CIGARETTES,CIGARS,CLEANING WIPES,CLEANSING WIPES,CLEMENTINES,CLOSET ACCESSORIES,CLOSET ORGNZRS: HNGRS/STORER,COCKTAIL MIXES-FLUID:ADD LIQ,COCKTAIL MIXES-FRZ,COCKTAILS,COCONUT,COFF SHOP: DANISH TAKE OUT,COFFEE,COFFEE FILTERS,COLD AND FLU,COLD AND FLU (AGE RESTRICTED),COLD AND FLU - DXM,COLD AND FLU - PSE,COLESLAW,COLLARS AND LEADS,COLLEGIATE,COLOR SETS,COMPACT FLUORESCENT LIGHT BULB,COMPUTING-MAGAZINE,CONDENSED SOUP,CONDIMENTS/SUPPLIES,CONES,CONSTRUCTION,CONSUMER BUNCH (NON-ROSE),CONTINUITY,CONTINUITY: FRAMES,CONVENTIONAL LITTER,COOKED,COOKIES/SWEET GOODS,COOKIES: GOURMET,COOKIES: HOLIDAY/SPECIAL OCCAS,COOKIES: MESSAGE,COOKIES: PARTY,COOKIES: REGULAR,COOKING BAGS,COOKING BAGS WITH SPICES/SEASO,COOKING CHOCOLATE (EX SMI-SWT),COOKING OIL: PEANUT SAFFLOWER,COOKING SPRAYS,COOKING WINES,COOKWARE,COOLERS,COORDINATES,CORN,CORN BEEF,CORN CHIPS,CORN DOGS,CORN FRESH PACKAGED,CORN OIL,CORN STARCH,CORN WHITE,CORN YELLOW,CORNED BEEF,CORNISH HEN,CORNMEAL,COSTUME ACCESSORIES,COSTUMES,COTTAGE CHEESE,COTTON COTTON SWABS,COUGH SYRP/LOZNG-DRP/XPCTRNT,COUPONS/STORE & MFG,COVERGIRL,CRACKERS,CRAFT BASICS,CRAFTS/SEWING-MAGAZINE,CRANAPPLE CRAN GRAPE JUICE (5,CRANAPPLE CRAN GRAPE JUICE (O,CRANBERRIES,CRANBERRY JUICE (50% AND UNDER,CRANBERRY JUICE (OVER 50% JCE),CRANBERRY SAUCE,CRAZY DAISIES,CREAM CHEESE,CROSSWORDS/PUZZLES-MAGAZINE,CROUTONS,CROUTONS SALAD TOPPERS BREAD,CUBED MEATS,CUCUMBERS,CUPS,CUPS/PUSH UPS/OTHER,CUT FRUIT ALL OTHER,CUT VEGETABLES ALL OTHER,CUTTING BOARDS,DAIRY CASE 100% PURE JUICE - O,DAIRY CASE 100% PURE JUICE OTH,DAIRY CASE CITRUS PNCH/OJ SUBS,DAIRY CASE FRUIT DRINKS (NO JU,DAIRY CASE JUICE DRNK UNDER 10,DAIRY CASE TEA WITH SUGAR OR S,DAIRY CHEESE,DANDRUFF-MEDICATED SHAMPOOS,DATES,DECAF BEAN: REGULAR,DECOR,DECOR BULBS,DELI TRAY:FRUIT AND VEGETABLE,DELI TRAY:MEAT AND CHEESE,DELI TRAY:SANDWICHES,DELUXE 25 STEMS & UP,DENTAL FLOSS AND IMPLEMENTS,DENTURE ADHESIVES,DENTURE CLEANSERS,DESIGNER FRAGRANCES,DESIGNER PAPER: MEDIUM WEIGHT,DESSERTS & VERMOUTH,DIECAST MINI,DIET CNTRL BARS NUTRITIONAL,DIET CNTRL LIQS NUTRITIONAL,DIET CNTRL POWDERS NUTRITIONAL,DIET CONTROL TABLETS/CAPSULE,DIET/LIGHT BREAD,DINNER ROLLS,DIPILATORIES,DIPS,DIPS (NON-REFRIGERATED),DISH GARDENS,DISPOSABLE FD STORAGE CONTAINR,DISPOSABLE FOILWARE,DISTILLED WATER,DIY ELECTRICAL,DL SPEC: DRY/REFRIG PASTAS,DL SPEC: MUST/OILS/VINEGARS,DL SPEC: SAUCES/SLD DRESSINGS,DOG & CAT ACCESSORIES,DOG & CAT CHEMICALS,DOG & CAT TOYS,DOG BISCUITS (HARD BISCUIT),DOG TREATS (SOFT TREATS),DOLLAR DAYS,DOMESTIC BIRD FOOD/NEEDS,DRAIN CARE,DRAIN CLEANING,DRESSINGS,DRIED FRUIT,DRIED FRUIT - OTHER,DRIED PLUMS,DRINKS - CARB JUICE (OVER 50%,DRUMS (IQF),DRY,DRY & SPRAY STARCH,DRY BEANS/PEAS/BARLEY: BAG & B,DRY CAT FOOD (CAT CHOW/FRISKIE,DRY CAT FOOD ECONOMY (COST CUT,DRY CAT FOOD SUP PREM (ONE/NUT,DRY DOG ECONOMY (COST CUTTER/F,DRY DOG FOOD PREMIUM (ALPO/PUR,DRY DOG FOOD SUPER PREM (ONE/N,DRY DOG VALUE (PET PRIDE/KLR/G,DRY ROAST NUTS,DRY SOUP,DVD PLAYERS,DVD S,EAR CARE,EASTER BASKET STUFFERS,EASTER BASKETS,EASTER EGG COLORING,EASTER FILL EGGS,EASTER GIFTWARE/DECOR,EASTER PLUSH,ECONOMY,ECONOMY - BEEF,ECONOMY - MEAT,EGG NOG/BOILED CUSTARD,EGGS,EGGS - JUMBO,EGGS - LARGE,EGGS - MEDIUM,EGGS - X-LARGE,EGGS SUBSTITUTE,ELECTRONIC GIFT CARDS ACTIVATI,ELECTRONIC GIFT CARDS REFRESH,ELSTC BNDGES SUPRT HOSE,ENERGY DRINK,ENGLISH MUFFINS/WAFFLES,ENHANCED,ENHANCED FLOWER DISPLAY,ENHANCEMENTS & POTCOVERS,ENTREES,ETHNIC HAIR CARE,ETHNIC-MAGAZINE,EVERYDAY MEDIUM,EXTENSION CORDS,EXTERNAL,EXTERNAL FRESH,EYE CARE ACCESSORIES,FABRIC REFRESHERS/DRY CLEAN,FABRIC SOFTENER LIQUID,FABRIC SOFTENER SHEETS,FACIAL CREAMS,FACIAL LOTIONS,FACIAL MOISTURIZERS,FACIAL SOAPS-SCRUBS-MASKS,FACIAL TISSUE & PAPER HANDKE,FALL & WINTER SEASONAL,FANS,FASHION PLAY,FASHION SLG,FASTENERS,FEEDING ACCESSORIES BOTTLES,FEM HYGN DOUCHES,FEM YEAST TREATMENTS,FEM. HYGN. DEODORANTS,FEM. HYGN. TAMPONS,FEM. HYGN.NAPKINS,FEMALE CONTRACEPTIVES,FIGHTING VARIETAL WINES,FILING SUPPLIES,FINISHED ELECTRICAL,FIRE STARTERS,FIREWOOD,FIRST AID MEDICATIONS,FIRSTAID TAPES/COTTON/GLOVES,FISHER PRICE,FITNESS&DIET - BARS,FITNESS&DIET-LIQ NTRTNL,FITNESS&HEALTH-MAGAZINE,FLAGS,FLANK,FLASHLIGHTS,FLATS,FLAVORED BEAN COFFEE,FLAVORED RUM (42 UNDER PROOF),FLAVORED/OTHER,FLEA/TICK COLLAR,FLNK/PLT/SHNK - STK/CHP/SLC,FLNK/PLT/SHNK - WH/HALF,FLOOR - CARPET & UPHOLSTERY,FLOOR - DILUTABLES,FLOOR - HARD SURFACE,FLORAL DEPT KEY RING,FLOUR: MISC SPECIALTY BLEND,FLOUR: WHITE & SELF RISING,FLOURS/GRAINS/SUGAR,FLOWERING PLANTS (5IN & DOWN),FLUID MILK,FLUID MILK WHITE ONLY,FLYING INSECT,FM-MLB,FM-NFL,FOAM PLATES,FOLIAGE HANGING BASKETS,FOLIAGE PLANTS-OTHER,FOOD COLORINGS,FOOD STORAGE BAGS,FOOD-MAGAZINE,FOOT CARE - MEDICATED CORN/CAL,FOOT CARE - SHOE INSOLE/PADS,FOOT SPRAYS POWDERS,FORTIFIED/ENERGY WATER,FRAGRANCED BATH PRODUCTS,FRAMES,FREEZER BAGS,FRENCH WINES,FRESH,FROSTING,FROZEN BREAD,FROZEN BREAKFAST,FROZEN BURGERS,FROZEN CAKES/ALL TYPES INCLUDI,FROZEN CONVENIENCE/POCKETS,FROZEN CREAM PIES,FROZEN ENTREES,FROZEN FRUIT,FROZEN FRUIT PIES & COBBLERS,FROZEN ICE CREAM,FROZEN MEAL COMBO/DINNERS,FROZEN MEAT,FROZEN MEAT (VEGETARIAN),FROZEN PACKAGE MEAT,FROZEN PASTA,FROZEN PIZZA,FROZEN VEGETABLES,FRUIT BOWL AND CUPS,FRUIT COCKTAIL FRUIT SALAD,FRUIT DRINKS: CANNED & GLASS (,FRUIT FILLED COOKIES,FRUIT GLAZES,FRUIT PARTY TRAY,FRUIT SNACKS,FRUIT VARIETAL WINES,FRUIT/BREAKFAST BREAD,FRZN BAGELS,FRZN BAGGED VEGETABLES - PLAIN,FRZN BAGGED VEGETABLES- VALUE,FRZN BAKED/STUFFED/MASHED&SPEC,FRZN BISCUITS,FRZN BOXED VEGETABLES - PLAIN,FRZN BOXED VEGETABLES- VALUE A,FRZN BRD OTHER,FRZN BRD STICK/PORTON,FRZN BRD WHOLE FILLETS,FRZN BREAD DOUGH,FRZN BREADED PREPARED CHICK,FRZN BREADED VEGETABLES,FRZN BREAKFAST ENTREES/SANDWIC,FRZN BREAKFAST PASTRY,FRZN BURGERS/BBQ/MEATBALL,FRZN CONC ALLIEDS OVER 50% JUI,FRZN CONC UNDER 50% JUICE,FRZN CORN ON THE COB,FRZN DINNER ROLLS,FRZN FRENCH FRIES,FRZN GARLIC BREAD/TOAST/STICKS,FRZN GRILLED PORTIONS,FRZN HASHBROWN POTATOES,FRZN MEAT ALTERNATIVES,FRZN MISC SEAFOOD,FRZN MULTI SERVE ENTREES ALL,FRZN OJ&OJ SUBSTITUTES (OVER 5,FRZN PASTRY&COOKIES,FRZN PIE SHELLS PASTRY SHELL,FRZN REGIONAL/OTHER,FRZN SS PREMIUM ENTREES/DNRS/N,FRZN SS PREMIUM ENTREES/DNRS/T,FRZN SWEET ROLLS&MUFFINS,FRZN TATER TOTS/OTHER EXTRUDED,FRZN WHIPPED TOPPING,FURNITURE,GADGETS/TOOLS,GAMES,GARBAGE KITCHEN COMPACTOR BA,GARDEN PLUS,GARDEN-MAGAZINE,GARLIC JAR,GARLIC WHOLE CLOVES,GAS CANS AND FUNNELS,GASOLINE-REG UNLEADED,GELATIN,GENERAL EYE CARE,GENERAL PURPOSE BULBS,GENERAL USE/MISC,GIFT TAGS,GIFT-WRAP EVERYDAY,GIFT-WRAP SEASONAL,GIFTWARE/DECOR,GLASS BAKEWARE,GLASS CLEANERS,GLASS FOOD STORAGE,GLOVES,GOURMET CHIPS (TERRA),GRAHAM CRACKERS,GRAINS,GRANOLA,GRANOLA BARS,GRAPE JUICE (50% AND UNDER JCE,GRAPE JUICE (OVER 50% JUICE),GRAPEFRUIT,GRAPEFRUIT JUICE (50% AND UNDE,GRAPEFRUIT JUICE (OVER 50% JUI,GRAPES BLACK/BLUE,GRAPES RED,GRAPES WHITE,GRASS/SHRED,GRATED CHEESE,GRAVY CAN/GLASS,GREAT GIFTS,GREEN OLIVES,GREEN ONIONS,GREENS,GRILL ACCESSORIES,GRITS,GRND/PATTY - BEEF,GRND/PATTY - CHUCK,GRND/PATTY - FROZEN,GRND/PATTY - ROUND,GRND/PATTY - SIRLOIN (90%+),GROUND CHICKEN,GROUND COFFEE,GROUND DECAFFINATED,GROUND FLVR DECAF COFFEE,GROUND FLVR REG COFFEE,GROUND PORK,GROUND TURKEY,GUM (PACKAGED),HAIR BARRETTES TAILERS,HAIR COLOR AND DEVELOPERS,HAIR COMBS AND BRUSHES,HAIR CONDITIONERS AND RINSES,HAIR DRYERS STYLERS SETTER,HAIR ROLLERS,HAIR SETS AND GELS,HAM,HAM - BONE-IN HALF/PORT,HAM - BONELESS WHOLE,HAM - SPIRAL,HAM - STEAKS/SLICES/CUBES,HAM STEAKS/CUBES/SLICES,HAM- NET WEIGHT,HAMBURGER BUNS,HAMS-DRY CURED/COUNTRY,HAMS-HALF/PORT BONE-IN,HAMS-HALF/PORT BONELESS,HAMS-SPIRAL,HAMS-WHOLE BONE-IN,HAMS-WHOLE BONELESS,HAND AND BODY CREAM,HAND AND BODY LOTIONS,HAND/BODY/FACIAL (MEDICATED),HANGERS,HANGING BASKETS (BLOOMING),HARD SQUASH,HARDBACK/TRADE BEST SELLER,HARDBACK/TRADE EVERYDAY,HASBRO,HASH: CANNED,HEAD LETTUCE,HEALING GARDEN,HEMORRHOIDAL,HERBS BASIL,HERBS CILANTO,HERBS DRIED,HERBS FRESH OTHER,HERBS PARSLEY,HISPANIC CARBONATED BEVERAGES,HISPANIC COOKIES/CRACKERS,HISPANIC JUICE UNDER 50% JUICE,HOBBIES-MAGAZINE,HOLDIAY DINNER (COLD),HOME DECOR-MAGAZINE,HOME PLANS-MAGAZINE,HOMINY,HONEY,HONEY/SYRUP,HONEYDEW WHOLE,HOT CHOCOLATE COCOA MIX,HOT DOG BUNS,HOT DOG CHILI SAUCE,HOT MUSTARD/SPECIALTY MUSTAR,HOT SAUCE,HOT/COLD COMPRESS PACKS,HYDROCORTIZONE,ICE - CRUSHED/CUBED,ICE CREAM SANDWICHES,ICE CREAM TOPPINGS,IMITATION EXTRACTS,IMPLEMENTS SETS,IN STORE MADE,INDIVIDUAL ORNAMENTS,INDOOR FLOODS AND SPOTS,INFANT FORMULA MILK BASE,INFANT FORMULA SOY BASE,INFANT FORMULA SPECIALTY,INFANT FORMULA TODDLER,INFLATABLES,INSIDE FROST BULBS,INSTANT BREAKFAST,INSTANT COFFEE FLAVORED NO SWE,INSTANT COFFEE FLAVORED W/SWEE,INSTANT COFFEE REGULAR,INSTANT DECAF FLVR COFFEE W/ S,INSTANT DECAFFINATED,INSTANT OATMEAL,INSTANT TEA & TEA MIX,INSTANT TEA & TEA MIX (W/SUGAR,INSTORE CUT FRUIT,INSTORE CUT VEGETABLES,INTERIOR/EXTERIOR ACCESSIORES,INTERIOR/EXTERIOR CARE,INTERNAL,IRONING ACCESSORIES: BRDS/CV,ISOTONIC DRINKS MULTI-SERVE,ISOTONIC DRINKS POWDERED,ISOTONIC DRINKS SINGLE SERVE,ITALIAN FOODS,ITALIAN WINES,IWS SINGLE CHEESE,JARRED FRUIT,JELLY,JHOOK - BABY,JHOOK - HOUSEHOLD,JHOOK - HOUSEWARE,JHOOK - MISC,JHOOK - PERSONAL CARE,JHOOK - TOYS,JUICE,JUICE (100% JUICE),JUICE (UNDER 10% JUICE),KABOBS,KABOBS BEEF,KABOBS PORK,KABOBS POULTRY,KEFIR,KIDS,KIDS CEREAL,KIDS/FAMILY,KITCHEN & BATHROOM DISPENSER C,KITCHEN & MULTI-PURPOSE CLEANE,KITCHEN TEXTILES,KITS,KIWI FRUIT,KOSHER FOODS,KOSHER/SPECIALTY,KRAUT & CABBAGE,LABELS/POST-IT/INDEX CARD,LADIES CASUAL SHOES,LADIES SANDALS,LADIES SHEER HOSIERY,LADIES SPORT SOCKS,LARGE - RICE CAKES,LAUNDRY,LAWN & LEAF BAGS,LAXATIVES,LAYER CAKE MIX,LEAN,LEGGS,LEMON JUICE & LIME JUICE (OVER,LEMONS,LIGHTS/ELECTRICS,LIMA BEANS,LIMES,LINAMENTS,LINKS - COOKED,LINKS - RAW,LIPCARE,LIPCARE MEDICATED,LIQUEURS/SPECIALTIES (42 UNDER,LIQUID BLEACH,LIQUID DISH DETERGENT,LIQUID LAUNDRY DETERGENTS,LIQUID NUTRITION FOR ADULTS,LIQUID SOAP,LITTER ACCESSORIES,LOAF CHEESE,LOAVE,LOIN - CHOPS BONE-IN,LOIN - CHOPS BONELESS,LOIN - ROAST,LOIN - STK/CHP/SLC,LOIN - WH/HALF BONE-IN,LOIN - WH/HALF BONELESS,LOREAL COSMETICS,LUNCH COMBO,LUNCHEON MEAT,MACARONI & CHEESE DNRS,MACARONI DRY,MACKEREL,MAIN MEAL BREAD,MAINSTREAM,MAINSTREAM WHEAT/MULTIGRAIN BR,MAINSTREAM WHITE BREAD,MAKE-UP/WIGS,MALE ACTION,MALTED MLK/SYRUP/PWDRS (EGGNOG,MANDARIN ORANGES/CITRUS SECT,MANGO,MARASCHINO CHERRIES,MARGARINE STICK,MARGARINE: SQUEEZE,MARGARINE: TUBS AND BOWLS,MARGARITA SALT/SUGAR MISC,MARINATED,MARINATED PORK,MARINATED POULTRY,MARSHMALLOW CREME,MARSHMALLOWS,MASKS,MASTERCARD GIFT CARD,MATCHES,MAX FACTOR,MAYBELLINE,MEAT ADDED,MEAT INCLUDED,MEAT SNACKS,MEAT SUPPLIES,MEAT: BEEF BULK,MEAT: BEEF PPK/PRESLCD,MEAT: CHICKEN BULK,MEAT: HAM PPK/PRSLC,MEAT: LUNCHMEAT BULK,MEAT: PATES/MOUSSE,MEAT: SAUS DRY BULK,MEAT: SAUS DRY PPK/PRSLC,MEAT: TURKEY BULK,MEAT: TURKEY PPK/PRESLC,MEAT:HAM BULK,MEDIA TAPE/BATTERIES,MELON HALVES/QUARTERS,MELONS WHOLE OTHER,MENS ACTIVEWEAR ADIDAS,MENS HAIR SPRAYS/TONICS/CREAMS,MENS SKIN CARE/COLOGNE,MENS-MAGAZINE,MENSTRUAL ANALGESICS,MESSAGE CENTER/SIGNING,METAL BAKEWARE,METAL POLISH&RUST REMOVERS,MEXICAN BEANS REFRIED,MEXICAN DINNERS AND FOODS,MEXICAN PEPPERS CHILIES,MEXICAN SAUCESSALSAPICANTEE,MEXICAN SEASONING MIXES,MEXICAN SOFT TORTILLAS AND WRA,MEXICAN TACO TOSTADO SHELLS,MICROWAVABLE CUPS,MICROWAVABLE SOUPS,MICROWAVE,MICROWAVE MIXES: ALL OTHER,MINI 2-5 STEMS,MINI DISC,MINI ORNAMENTS,MINTS CANDY & BREATH (NOT LIF,MINUET,MISC,MISC BAG SNACKS,MISC BUDGET COSMETICS,MISC CARRIER,MISC CHECKLANE CANDY,MISC CHEMICALS,MISC CND MEATS,MISC DAIRY REFIGERATED,MISC FEMININE HYGIENE MEDICATE,MISC GRAIN MIXES,MISC GREETING CARD SHOP,MISC HOLIDAYS,MISC MEAT SAUCES,MISC ORAL HYGN MEDICATED (DESE,MISC REFRIG DOUGH PRODUCTS,MISC REPAIR,MISC SALES TRANS,MISC SNACKS,MISC. BABY PRODUCTS,MISC. BATH PRODUCTS,MISC. CEREAL,MISC. COOKNG/BKNGWARES,MISC. DEODORANTS,MISC. FACIAL PRODUCTS,MISC. FEMININE HYGIENE,MISC. FIRST AID PRODUCTS,MISC. HAIR & BEAUTY ACCESS.,MISC. HAIR CARE,MISC. INFANT SUPPLY,MISC. LAWN & GARDEN,MISC. PET SUPPLIES,MISC. SEASONAL ITEMS,MISC.CND SEAFOODS (CRABETC),MISC: CHEESECAKE MOUSSE MIXES,MISC: HERRING PICKLES HORSER,MISCELLANEOUS,MISCELLANEOUS CANDY (INCLUDING,MISCELLANEOUS CHEESE,MISCELLANEOUS H & B AIDS,MISCELLANEOUS HOLIDAY GIFTWARE,MISCELLANEOUS MILK,MISCELLANEOUS PACKAGE MIXES,MISCELLANEOUS VEGETABLES,MIXED FRUIT BAGS,MIXED VEGETABLES,MIXERS(CLUB SODA/SELTZERS)FLAV,MIXERS(TONIC WTR/CLUB SODA/GNG,MIXERS(TONIC WTR/GNGR ALE)FLAV,MIXES,MOLASSES & SYRUPS,MOPS: SPONGE DECK DUST,MOTOR/TRANS/MISC OIL,MOTORCYCLE-MAGAZINE,MOUTH SORE MEDICATED,MOUTHWASH RINSES AND SPRAYS,MUFFIN & CORN BREAD MIX,MULT PK BAG SNACKS,MULTI-PACK COOKIES,MULTI-PACK CRACKERS,MUMS,MUSHROOMS CND & GLASS,MUSHROOMS OTHER,MUSHROOMS PORTABELLA,MUSHROOMS W/WHOLE PKG,MUSHROOMS WHITE BULK,MUSHROOMS WHITE SLICED PKG,MUSIC-MAGAZINE,N/A DEOD SPRAY/GEL DEOD,NAILCARE,NASAL SPRAY AND DROPS,NATURAL,NATURAL BEEF,NATURAL CHEESE EXACT WT CHUNKS,NATURAL CHEESE EXACT WT SLICES,NECTARINES WHITE FLESH,NECTARINES YELLOW FLESH,NERF ITEMS,NEWS-MAGAZINE,NEWSPAPER,NIGHT LIGHTS,NO SUBCOMMODITY DESCRIPTION,NO-NONSENSE,NON DAIRY CREAMER: DRY,NON FAT DRY MILK,NON-CARB FLVRD DRNKNG/MNRL WAT,NON-CARB FLVRD UNSWEETENED WAT,NON-CARB JCE (UNDER 50%JCE),NON-CARB JCE(OVER 50% JCE),NON-CARB WATER FLVR - DRNK/MNR,NON-CRBNTD DRNKING/MNERAL WATE,NON-DAIRY CHEESE,NON-IWS SINGLE CHEESE,NON-MEATS - OTHER,NOODLE SIDE DISH MIXES,NOODLES DRY,NOVELTIES,NOVELTY CANDY,NOVELTY FIREWORKS,NUT BUTTERS/PEANUT BUTTER,NUTS,NUTS INSHELL,NUTS OTHER,OFFALS,OFFICE PAPER,OILS/VINEGAR,OLIVE OIL,ONE HOUR PROCESSING,ONIONS OTHER,ONIONS RED (BULK&BAG),ONIONS SWEET (BULK&BAG),ONIONS WHITE (BULK&BAG),ONIONS YELLOW (BULK&BAG),ORAL HYGIENE BRUSHES,ORANGE JUICE (OVER 50% JUICE),ORANGES NAVELS ALL,ORANGES NON NAVEL ALL,ORGANIC APPLES,ORGANIC BERRIES,ORGANIC BROCCOLI/CAULIFLOWER,ORGANIC CARROTS,ORGANIC CITRUS,ORGANIC DRIED FRUIT,ORGANIC GRAPES,ORGANIC HERBS,ORGANIC MUSHROOMS,ORGANIC ONIONS,ORGANIC PEPPERS ALL,ORGANIC

In [59]:
household_item_matrix.shape

(2500, 1677)

In [60]:
from sklearn.metrics.pairwise import cosine_similarity
similarity_matrix = cosine_similarity(household_item_matrix)
similarity_matrix

array([[1.00000000e+00, 3.76361471e-01, 4.28902872e-03, ...,
        1.16478745e-03, 3.21663373e-04, 2.10165628e-04],
       [3.76361471e-01, 1.00000000e+00, 9.12665269e-03, ...,
        1.28083167e-03, 4.66291642e-04, 2.97045944e-04],
       [4.28902872e-03, 9.12665269e-03, 1.00000000e+00, ...,
        9.99572543e-01, 9.99562603e-01, 9.99553959e-01],
       ...,
       [1.16478745e-03, 1.28083167e-03, 9.99572543e-01, ...,
        1.00000000e+00, 9.99995499e-01, 9.99995372e-01],
       [3.21663373e-04, 4.66291642e-04, 9.99562603e-01, ...,
        9.99995499e-01, 1.00000000e+00, 9.99999290e-01],
       [2.10165628e-04, 2.97045944e-04, 9.99553959e-01, ...,
        9.99995372e-01, 9.99999290e-01, 1.00000000e+00]],
      shape=(2500, 2500))

In [61]:
similarity_df = pd.DataFrame(similarity_matrix, index = household_item_matrix.index, columns = household_item_matrix.index)
similarity_df.head()

household_key,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767,768,769,770,771,772,773,774,775,776,777,778,779,780,781,782,783,784,785,786,787,788,789,790,791,792,793,794,795,796,797,798,799,800,801,802,803,804,805,806,807,808,809,810,811,812,813,814,815,816,817,818,819,820,821,822,823,824,825,826,827,828,829,830,831,832,833,834,835,836,837,838,839,840,841,842,843,844,845,846,847,848,849,850,851,852,853,854,855,856,857,858,859,860,861,862,863,864,865,866,867,868,869,870,871,872,873,874,875,876,877,878,879,880,881,882,883,884,885,886,887,888,889,890,891,892,893,894,895,896,897,898,899,900,901,902,903,904,905,906,907,908,909,910,911,912,913,914,915,916,917,918,919,920,921,922,923,924,925,926,927,928,929,930,931,932,933,934,935,936,937,938,939,940,941,942,943,944,945,946,947,948,949,950,951,952,953,954,955,956,957,958,959,960,961,962,963,964,965,966,967,968,969,970,971,972,973,974,975,976,977,978,979,980,981,982,983,984,985,986,987,988,989,990,991,992,993,994,995,996,997,998,999,1000,1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023,1024,1025,1026,1027,1028,1029,1030,1031,1032,1033,1034,1035,1036,1037,1038,1039,1040,1041,1042,1043,1044,1045,1046,1047,1048,1049,1050,1051,1052,1053,1054,1055,1056,1057,1058,1059,1060,1061,1062,1063,1064,1065,1066,1067,1068,1069,1070,1071,1072,1073,1074,1075,1076,1077,1078,1079,1080,1081,1082,1083,1084,1085,1086,1087,1088,1089,1090,1091,1092,1093,1094,1095,1096,1097,1098,1099,1100,1101,1102,1103,1104,1105,1106,1107,1108,1109,1110,1111,1112,1113,1114,1115,1116,1117,1118,1119,1120,1121,1122,1123,1124,1125,1126,1127,1128,1129,1130,1131,1132,1133,1134,1135,1136,1137,1138,1139,1140,1141,1142,1143,1144,1145,1146,1147,1148,1149,1150,1151,1152,1153,1154,1155,1156,1157,1158,1159,1160,1161,1162,1163,1164,1165,1166,1167,1168,1169,1170,1171,1172,1173,1174,1175,1176,1177,1178,1179,1180,1181,1182,1183,1184,1185,1186,1187,1188,1189,1190,1191,1192,1193,1194,1195,1196,1197,1198,1199,1200,1201,1202,1203,1204,1205,1206,1207,1208,1209,1210,1211,1212,1213,1214,1215,1216,1217,1218,1219,1220,1221,1222,1223,1224,1225,1226,1227,1228,1229,1230,1231,1232,1233,1234,1235,1236,1237,1238,1239,1240,1241,1242,1243,1244,1245,1246,1247,1248,1249,1250,1251,1252,1253,1254,1255,1256,1257,1258,1259,1260,1261,1262,1263,1264,1265,1266,1267,1268,1269,1270,1271,1272,1273,1274,1275,1276,1277,1278,1279,1280,1281,1282,1283,1284,1285,1286,1287,1288,1289,1290,1291,1292,1293,1294,1295,1296,1297,1298,1299,1300,1301,1302,1303,1304,1305,1306,1307,1308,1309,1310,1311,1312,1313,1314,1315,1316,1317,1318,1319,1320,1321,1322,1323,1324,1325,1326,1327,1328,1329,1330,1331,1332,1333,1334,1335,1336,1337,1338,1339,1340,1341,1342,1343,1344,1345,1346,1347,1348,1349,1350,1351,1352,1353,1354,1355,1356,1357,1358,1359,1360,1361,1362,1363,1364,1365,1366,1367,1368,1369,1370,1371,1372,1373,1374,1375,1376,1377,1378,1379,1380,1381,1382,1383,1384,1385,1386,1387,1388,1389,1390,1391,1392,1393,1394,1395,1396,1397,1398,1399,1400,1401,1402,1403,1404,1405,1406,1407,1408,1409,1410,1411,1412,1413,1414,1415,1416,1417,1418,1419,1420,1421,1422,1423,1424,1425,1426,1427,1428,1429,1430,1431,1432,1433,1434,1435,1436,1437,1438,1439,1440,1441,1442,1443,1444,1445,1446,1447,1448,1449,1450,1451,1452,1453,1454,1455,1456,1457,1458,1459,1460,1461,1462,1463,1464,1465,1466,1467,1468,1469,1470,1471,1472,1473,1474,1475,1476,1477,1478,1479,1480,1481,1482,1483,1484,1485,1486,1487,1488,1489,1490,1491,1492,1493,1494,1495,1496,1497,1498,1499,1500,1501,1502,1503,1504,1505,1506,1507,1508,1509,1510,1511,1512,1513,1514,1515,1516,1517,1518,1519,1520,1521,1522,1523,1524,1525,1526,1527,1528,1529,1530,1531,1532,1533,1534,1535,1536,1537,1538,1539,1540,1541,1542,1543,1544,1545,1546,1547,1548,1549,1550,1551,1552,1553,1554,1555,1556,1557,1558,1559,1560,1561,1562,1563,1564,1565,1566,1567,1568,1569,1570,1571,1572,1573,1574,1575,1576,1577,1578,1579,1580,1581,1582,1583,1584,1585,1586,1587,1588,1589,1590,1591,1592,1593,1594,1595,1596,1597,1598,1599,1600,1601,1602,1603,1604,1605,1606,1607,1608,1609,1610,1611,1612,1613,1614,1615,1616,1617,1618,1619,1620,1621,1622,1623,1624,1625,1626,1627,1628,1629,1630,1631,1632,1633,1634,1635,1636,1637,1638,1639,1640,1641,1642,1643,1644,1645,1646,1647,1648,1649,1650,1651,1652,1653,1654,1655,1656,1657,1658,1659,1660,1661,1662,1663,1664,1665,1666,1667,1668,1669,1670,1671,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682,1683,1684,1685,1686,1687,1688,1689,1690,1691,1692,1693,1694,1695,1696,1697,1698,1699,1700,1701,1702,1703,1704,1705,1706,1707,1708,1709,1710,1711,1712,1713,1714,1715,1716,1717,1718,1719,1720,1721,1722,1723,1724,1725,1726,1727,1728,1729,1730,1731,1732,1733,1734,1735,1736,1737,1738,1739,1740,1741,1742,1743,1744,1745,1746,1747,1748,1749,1750,1751,1752,1753,1754,1755,1756,1757,1758,1759,1760,1761,1762,1763,1764,1765,1766,1767,1768,1769,1770,1771,1772,1773,1774,1775,1776,1777,1778,1779,1780,1781,1782,1783,1784,1785,1786,1787,1788,1789,1790,1791,1792,1793,1794,1795,1796,1797,1798,1799,1800,1801,1802,1803,1804,1805,1806,1807,1808,1809,1810,1811,1812,1813,1814,1815,1816,1817,1818,1819,1820,1821,1822,1823,1824,1825,1826,1827,1828,1829,1830,1831,1832,1833,1834,1835,1836,1837,1838,1839,1840,1841,1842,1843,1844,1845,1846,1847,1848,1849,1850,1851,1852,1853,1854,1855,1856,1857,1858,1859,1860,1861,1862,1863,1864,1865,1866,1867,1868,1869,1870,1871,1872,1873,1874,1875,1876,1877,1878,1879,1880,1881,1882,1883,1884,1885,1886,1887,1888,1889,1890,1891,1892,1893,1894,1895,1896,1897,1898,1899,1900,1901,1902,1903,1904,1905,1906,1907,1908,1909,1910,1911,1912,1913,1914,1915,1916,1917,1918,1919,1920,1921,1922,1923,1924,1925,1926,1927,1928,1929,1930,1931,1932,1933,1934,1935,1936,1937,1938,1939,1940,1941,1942,1943,1944,1945,1946,1947,1948,1949,1950,1951,1952,1953,1954,1955,1956,1957,1958,1959,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,2027,2028,2029,2030,2031,2032,2033,2034,2035,2036,2037,2038,2039,2040,2041,2042,2043,2044,2045,2046,2047,2048,2049,2050,2051,2052,2053,2054,2055,2056,2057,2058,2059,2060,2061,2062,2063,2064,2065,2066,2067,2068,2069,2070,2071,2072,2073,2074,2075,2076,2077,2078,2079,2080,2081,2082,2083,2084,2085,2086,2087,2088,2089,2090,2091,2092,2093,2094,2095,2096,2097,2098,2099,2100,2101,2102,2103,2104,2105,2106,2107,2108,2109,2110,2111,2112,2113,2114,2115,2116,2117,2118,2119,2120,2121,2122,2123,2124,2125,2126,2127,2128,2129,2130,2131,2132,2133,2134,2135,2136,2137,2138,2139,2140,2141,2142,2143,2144,2145,2146,2147,2148,2149,2150,2151,2152,2153,2154,2155,2156,2157,2158,2159,2160,2161,2162,2163,2164,2165,2166,2167,2168,2169,2170,2171,2172,2173,2174,2175,2176,2177,2178,2179,2180,2181,2182,2183,2184,2185,2186,2187,2188,2189,2190,2191,2192,2193,2194,2195,2196,2197,2198,2199,2200,2201,2202,2203,2204,2205,2206,2207,2208,2209,2210,2211,2212,2213,2214,2215,2216,2217,2218,2219,2220,2221,2222,2223,2224,2225,2226,2227,2228,2229,2230,2231,2232,2233,2234,2235,2236,2237,2238,2239,2240,2241,2242,2243,2244,2245,2246,2247,2248,2249,2250,2251,2252,2253,2254,2255,2256,2257,2258,2259,2260,2261,2262,2263,2264,2265,2266,2267,2268,2269,2270,2271,2272,2273,2274,2275,2276,2277,2278,2279,2280,2281,2282,2283,2284,2285,2286,2287,2288,2289,2290,2291,2292,2293,2294,2295,2296,2297,2298,2299,2300,2301,2302,2303,2304,2305,2306,2307,2308,2309,2310,2311,2312,2313,2314,2315,2316,2317,2318,2319,2320,2321,2322,2323,2324,2325,2326,2327,2328,2329,2330,2331,2332,2333,2334,2335,2336,2337,2338,2339,2340,2341,2342,2343,2344,2345,2346,2347,2348,2349,2350,2351,2352,2353,2354,2355,2356,2357,2358,2359,2360,2361,2362,2363,2364,2365,2366,2367,2368,2369,2370,2371,2372,2373,2374,2375,2376,2377,2378,2379,2380,2381,2382,2383,2384,2385,2386,2387,2388,2389,2390,2391,2392,2393,2394,2395,2396,2397,2398,2399,2400,2401,2402,2403,2404,2405,2406,2407,2408,2409,2410,2411,2412,2413,2414,2415,2416,2417,2418,2419,2420,2421,2422,2423,2424,2425,2426,2427,2428,2429,2430,2431,2432,2433,2434,2435,2436,2437,2438,2439,2440,2441,2442,2443,2444,2445,2446,2447,2448,2449,2450,2451,2452,2453,2454,2455,2456,2457,2458,2459,2460,2461,2462,2463,2464,2465,2466,2467,2468,2469,2470,2471,2472,2473,2474,2475,2476,2477,2478,2479,2480,2481,2482,2483,2484,2485,2486,2487,2488,2489,2490,2491,2492,2493,2494,2495,2496,2497,2498,2499,2500
household_key,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,

In [62]:
# cosine similarity
def get_similar_households(household_id):
    similarities = similarity_df.loc[household_id].sort_values(ascending = False).iloc[1:6]
    return similarities

In [63]:
get_similar_households(1)

household_key
1064    0.463453
1590    0.457699
1719    0.445255
1908    0.432980
2181    0.431268
Name: 1, dtype: float64

In [64]:
get_similar_households(2000)

household_key
407    0.669443
358    0.613822
136    0.599582
930    0.598569
290    0.598268
Name: 2000, dtype: float64

In [65]:
get_similar_households(17)

household_key
176     0.999999
588     0.999999
963     0.999999
2093    0.999999
1299    0.999999
Name: 17, dtype: float64

In [66]:
get_similar_households(18)

household_key
1612    1.0
1944    1.0
949     1.0
744     1.0
2311    1.0
Name: 18, dtype: float64

In [67]:
# top 5 recs per household
count = 0
for i in range(1,2501):
    
    val = get_similar_households(i).iloc[0]
    if val > 0.9:
        count += 1
        print(val, count)

0.9997023580992275 1
0.9999964655400603 2
0.9999967453403237 3
0.9999999802793325 4
0.999999637852833 5
0.9999996760676475 6
0.9999994694367884 7
0.9999995834378735 8
0.9999997817891497 9
0.9999996891497898 10
0.9999979303783336 11
0.999999911681041 12
0.9999997833054977 13
0.9999927105248819 14
0.9999969151640152 15
0.9999999228597438 16
0.9999999544523995 17
0.9999999539746749 18
0.9999978592606531 19
0.9999966411410244 20
0.9999995019556078 21
0.9995299802639839 22
0.9999857919830529 23
0.9998940580874885 24
0.999999942378852 25
0.9999985627186357 26
0.9999982348614996 27
0.9999989175846674 28
0.9999997340396121 29
0.9999997505289693 30
0.9999992838801889 31
0.9995310440834096 32
0.999998581139147 33
0.9999999806282766 34
0.9999986349147995 35
0.9999991051425899 36
0.999999697297452 37
0.9999991235090102 38
0.9999640499690038 39
0.9999990827393277 40
0.9999999258983594 41
0.9999999753105941 42
0.9999998295388044 43
0.9999995389589914 44
0.999999035418162 45
0.9999673060845784 46
0.9999991862883284 47
0.9999713899156379 48
0.9999991734318618 49
0.9999989269937859 50
0.9999998794789764 51
0.9999758522920363 52
0.9999417909933684 53
0.9999989272868732 54
0.9999998627069632 55
0.999999895221792 56
0.9999781931135185 57
0.999999727173316 58
0.9999993994683792 59
0.9999728602518229 60
0.9999999657952009 61
0.9999999556720185 62
0.9999992503848829 63
0.9999998104996348 64
0.9999991735043195 65
0.9999999723448941 66
0.9999999488474425 67
0.999997267622691 68
0.9999999418009501 69
0.9999848146099932 70
0.9999989938325031 71
0.9999997717949147 72
0.9999807253390406 73
0.9999992489696276 74
0.9999999654895292 75
0.9999998991973965 76
0.9999982802666992 77
0.9999998083111689 78
0.9999991034773996 79
0.9999607513158503 80
0.9999875898885306 81
0.9999981917222938 82
0.9999985409164402 83
0.9999995683158093 84
0.9999986954994047 85
0.999999234511785 86
0.9999999703279259 87
0.9999993722433043 88
0.9893474878842844 89
0.9999977856059211 90
0.9999643161740599 91
0.999999746339894 92
0.9999790063288854 93
0.9998748267893481 94
0.9999983922015787 95
0.9999941994830601 96
0.9999991919776313 97
0.999993063405767 98
0.9999999195350711 99
0.999999172076474 100
0.9999999847685801 101
0.9999831709030509 102
0.999987472795561 103
0.9999999674590494 104
0.9999998122409027 105
0.9999995627323311 106
0.9991302805793636 107
0.999999915888943 108
0.9999999170701693 109
0.9999995546769173 110
0.9999980570673878 111
0.9999992015191163 112
0.9999993402742308 113
0.9999999798592679 114
0.9999986439578167 115
0.9999998952570647 116
0.9999947386239755 117
0.9999990898434922 118
0.9999998921812003 119
0.9999994988377293 120
0.9999763388835156 121
0.9999961293007229 122
0.9999997401078311 123
0.9999997811297081 124
0.99955154893705 125
0.9999980041574663 126
0.9999978140766899 127
0.9999999112861058 128
0.9999999550590135 129
0.9999971702738121 130
0.9999996969151069 131
0.999985986039825 132
0.9999989411765642 133
0.9999933995524029 134
0.999973974602203 135
0.999999180774224 136
0.9997834444184747 137
0.9999994991940032 138
0.99999906812555 139
0.999999510083026 140
0.9999995230616027 141
0.999999673124704 142
0.9999999376159812 143
0.9999999062492642 144
0.9998576833961624 145
0.9999964260954877 146
0.9999740159675671 147
0.9999115246937906 148
0.9999929568637881 149
0.9999957990501793 150
0.9999415684927035 151
0.9999902877449028 152
0.9999929533258279 153
0.9999999648102706 154
0.9999827823883823 155
0.9996803734964443 156
0.999998649432909 157
0.9999839832291038 158
0.9999940001283038 159
0.9999934411796787 160
0.9999979637428527 161
0.9999988151241564 162
0.9999998195765694 163
0.9999998761823858 164
0.9999998232778141 165
0.99994538782916 166
0.9999996298689785 167
0.9999990576741936 168
0.9999995375117731 169
0.9999995345868601 170
0.999999921523686 171
0.9999999643757618 172
0.9999742826802084 173
0.9997488793594038 174
0.9999999684005911 175
0.9998549783252634 176
0.9999754048959036 177
0.9999969028367316 178
0.9999998867027826 179
0.9999997294557709 180
0.9999997746535618 181
0.9999918414186987 182
0.9999995589492663 183
0.9999991154915475 184
0.9999996912582088 185
0.9999807963709298 186
0.9999857412943016 187
0.9999998394716975 188
0.9999837293750382 189
0.9999204850113638 190
0.9999999552707206 191
0.9999762162922514 192
0.9999992825942061 193
0.9999986512754114 194
0.999972758513721 195
0.9999990064502775 196
0.9999959781499079 197
0.9999473517986155 198
0.944655760890717 199
0.9999998274635701 200
0.9999973015349066 201
0.9999999456728869 202
0.9999844101075853 203
0.9999998434813622 204
0.9999993510590025 205
0.9999968926392271 206
0.9999574830644243 207
0.9999988925088583 208
0.9972337698259882 209
0.9999991228672277 210
0.9999939907963644 211
0.9999999206910167 212
0.9999926969082775 213
0.9999988011042603 214
0.9999973250513203 215
0.9999991317920914 216
0.9999366169869395 217
0.9999997673312354 218
0.9999989646579971 219
0.9999992939710334 220
0.9999984691997746 221
0.9999979669636098 222
0.9998888308321153 223
0.9999996009648904 224
0.999978421898696 225
0.9999977542512518 226
0.9999998742769722 227
0.9999997272351975 228
0.9999996261029501 229
0.9999999267591608 230
0.9999998447495547 231
0.9999993095043905 232
0.9999999492654187 233
0.9999985100329306 234
0.9443170514571987 235
0.999999764089174 236
0.9999992763237628 237
0.9999516904669381 238
0.9999998468535046 239
0.9999990988953512 240
0.9999998083249512 241
0.9999985370580048 242
0.9999999654608167 243
0.9999999712585678 244
0.9999365375548432 245
0.999998452148276 246
0.9987838197805562 247
0.9999996767550329 248
0.9999997035842909 249
0.9030507458705793 250
0.99999090807981 251
0.9999991974812777 252
0.9999997416193112 253
0.9999988108788078 254
0.9995356452186634 255
0.999943500478472 256
0.9999960336632461 257
0.999993139166505 258
0.9999993520388328 259
0.9999993453226846 260
0.9999999156425048 261
0.9999987865112803 262
0.9998696722798409 263
0.999998572527512 264
0.9999985209507474 265
0.9999402588216616 266
0.9999998491681729 267
0.9999998893529298 268
0.9999997518503381 269
0.9999999368578183 270
0.9996992141418516 271
0.9999654648698001 272
0.9999999608947294 273
0.9999995115021038 274
0.9999999027076545 275
0.999618343212472 276
0.9999999321709006 277
0.9999998937122191 278
0.9999996480433458 279
0.9999334475107973 280
0.9995999235569683 281
0.9999997403241326 282
0.9999947916932029 283
0.9999998264359528 284
0.9999996615554922 285
0.999997129153506 286
0.9982255720049457 287
0.9999697514381001 288
0.9999996279061674 289
0.9999661684858364 290
0.9994113835663611 291
0.9999998022317117 292
0.9998713390721146 293
0.999999946144968 294
0.9999769418040754 295
0.9999925998150359 296
0.9997847292164526 297
0.9999877094545973 298
0.9999998779404708 299
0.9999989751955594 300
0.9999973495890452 301
0.9999995772996949 302
0.9999915517142142 303
0.9999328225457756 304
0.9999988773804313 305
0.9999364493793416 306
0.9999934522372197 307
0.9999962753478245 308
0.9999999659078416 309
0.9999955251878795 310
0.9999999382187716 311
0.9999987776841416 312
0.9999946518072579 313
0.9999998768986036 314
0.9999994394873065 315
0.999999456372226 316
0.9999789658523879 317
0.9999959400268504 318
0.9999909217188714 319
0.999828924814851 320
0.999999625233506 321
0.9999983838568209 322
0.9999986867315085 323
0.9999917986594181 324
0.9999784434545854 325
0.9999982341786655 326
0.9999575598616282 327
0.9998774601313309 328
0.9999992855579459 329
0.9999999710559219 330
0.9999934699647921 331
0.9999996585306842 332
0.999991089506695 333
0.9999998873188493 334
0.9999936967263457 335
0.9999937066740722 336
0.9999974029411994 337
0.9995844753869896 338
0.9999984227288533 339
0.9999998425541528 340
0.9999995150449539 341
0.9999997936833308 342
0.9999996288394492 343
0.9999998775159773 344
0.9999880096329747 345
0.9999992983560195 346
0.9999980872297054 347
0.999999957913379 348
0.9999996636960975 349
0.999999845598649 350
0.9999999378658193 351
0.9999995424681832 352
0.9998093430229728 353
0.9999986376218295 354
0.9999996011127629 355
0.9997016331679763 356
0.9999991279497304 357
0.9999990105906671 358
0.999999916330559 359
0.9999998153774038 360
0.9999998506173422 361
0.9999997144668398 362
0.9999823011166069 363
0.9997087567282105 364
0.9999999621486612 365
0.9999994545563439 366
0.9999869611953759 367
0.9999910833523444 368
0.9999990476956718 369
0.9999998267315735 370
0.9999999301891273 371
0.9999999073980362 372
0.9999996786426537 373
0.999992277626924 374
0.999999356403511 375
0.9999865439427661 376
0.9999994795706788 377
0.9999917157592909 378
0.9999998446685097 379
0.9999999124613385 380
0.9999974913953642 381
0.9999998154033349 382
0.999999796957237 383
0.9999791748816416 384
0.9999999625353674 385
0.9999966404869384 386
0.9999696707647263 387
0.9999996828394209 388
0.9999996579459925 389
0.9999998920833587 390
0.9999999300602486 391
0.9999997834014406 392
0.9999920540984809 393
0.9999998863890625 394
0.9999702048120669 395
0.9999996093139669 396
0.999999971004159 397
0.9999976118643822 398
0.9999998731104223 399
0.9999999754138892 400
0.9999979116842048 401
0.9999965837803215 402
0.9999983970913919 403
0.9999987853159666 404
0.9998000948628831 405
0.9999929255768054 406
0.9999998831039387 407
0.9999998358688309 408
0.9999960111628889 409
0.9999967606719452 410
0.9999964950179782 411
0.9999872029444011 412
0.9999998746389286 413
0.9999998723709014 414
0.9999988522607682 415
0.9999990683651301 416
0.9999918101772943 417
0.9935600725881821 418
0.9999977826124862 419
0.9999884547758865 420
0.9999807963709298 421
0.9999999301332716 422
0.9999999383883625 423
0.9997756880617917 424
0.9999907503437989 425
0.9999999634190523 426
0.9999999988124104 427
0.9999946978204148 428
0.9999983775713795 429
0.9999979752883479 430
0.9998451032178455 431
0.9999995241473357 432
0.9999997591343601 433
0.9988104965637595 434
0.9999998361917223 435
0.9999999301373501 436
0.9999997816088033 437
0.9999643895072289 438
0.9999993944345706 439
0.9961474666808331 440
0.9999985372998568 441
0.9999445085458086 442
0.9999999537436811 443
0.9999991858172141 444
0.9999982169914791 445
0.9999999104052044 446
0.9999999038974308 447
0.9999982947553158 448
0.9999716212720091 449
0.9999977802035078 450
0.9999997202794904 451
0.9999921900026595 452
0.9999975668961973 453
0.9999995891360427 454
0.9999853131194815 455
0.9999971965229546 456
0.9999910790674849 457
0.999999697897916 458
0.9999997455359364 459
0.9999930719089084 460
0.9999845524200857 461
0.9999829168537605 462
0.9999999547282852 463
0.9999381033196895 464
0.9999995426656472 465
0.9999888110251529 466
0.9999997703569918 467
0.9999796839751298 468
0.9999999596364955 469
0.9999888554192453 470
0.999999528042716 471
0.9999995136798379 472
0.9999726661937087 473
0.9999922881140707 474
0.9999996984493634 475
0.9999919481984435 476
0.9999718822656378 477
0.9999994701478082 478
0.99999983487196 479
0.9997388774508278 480
0.9998624855260133 481
0.9999988007652281 482
0.9999999205451299 483
0.999929873111564 484
0.9999997409492205 485
0.9999993398026631 486
0.9999996284323098 487
0.9999998368377492 488
0.9999968884217164 489
0.9999992361214598 490
0.9999998722477081 491
0.9999999623945923 492
0.9999963254364885 493
0.9999993215848076 494
0.9999997924593985 495
0.9999985937035629 496
0.9999788481859108 497
0.9999999457984717 498
0.9999986331388759 499
0.9999998648976244 500
0.9999965164263336 501
0.9999996827124423 502
0.9999999311961513 503
0.9999838111894888 504
0.9998965178062161 505
0.9999994063659383 506
0.9999994400923589 507
0.999999900321254 508
0.932763992190526 509
0.9999998863890625 510
0.9992474156414086 511
0.9999993984864597 512
0.9999999270288931 513
0.9999995548079711 514
0.9999994038179058 515
0.9999999633171236 516
0.9999996246814136 517
0.9999977147967959 518
0.9999309378281402 519
0.9999983604754248 520
0.999999793063627 521
0.9993915201701723 522
0.9998339929972909 523
0.9999985726064659 524
0.9999998199530398 525
0.9999999543832403 526
0.9999999259665509 527
0.9999993587170558 528
0.9999994269033929 529
0.9443170514571987 530
0.9999938971357581 531
0.9948830544454158 532
0.9999987887995037 533
0.9999959264997689 534
0.9999999914398765 535
0.9999852958053791 536
0.9997905795183314 537
0.9999711723544574 538
0.9998160579160561 539
0.9999997759763579 540
0.9999443030626697 541
0.9999986989705304 542
0.9999999796278024 543
0.9999946785444546 544
0.9997916093735995 545
0.9999999021519558 546
0.9999980677709015 547
0.9999998824511585 548
0.9999963368124944 549
0.9999715683808638 550
0.9999966291801066 551
0.9999999639446352 552
0.9999960183680651 553
0.9999997864584675 554
0.9999750491929541 555
0.9030507458705793 556
0.9999998614157931 557
0.9994506640966436 558
0.999999478764397 559
0.9995694213717735 560
0.9999992313944259 561
0.99998873153328 562
0.9999951088126359 563
0.999999942631394 564
0.9999468219657615 565
0.9999993862914782 566
0.9999972727813622 567
0.9999999105598827 568
0.999999601228423 569
0.9999998610990666 570
0.9999969291428333 571
0.9999999394034711 572
0.9999873360540916 573
0.9999996404938899 574
0.9998505917817193 575
0.9998908771059564 576
0.9999983799397077 577
0.9999996162198508 578
0.999993048663768 579
0.9999999585120138 580
0.9999994136723772 581
0.9998974540489075 582
0.9999999917127751 583
0.9999999305490408 584
0.9999999243287924 585
0.9999997850813751 586
0.9998730324426283 587
0.999998601787397 588
0.9998415342555437 589
0.9999921340079572 590
0.9999972426328245 591
0.9999804295858014 592
0.9999999896381072 593
0.999995958109225 594
0.999999963840775 595
0.9999999401077078 596
0.9999920869553632 597
0.9999996103508758 598
0.999998307169992 599
0.9999929202681196 600
0.9999999648431802 601
0.9999993645484302 602
0.9999999578978741 603
0.9999999763421372 604
0.9999941542716795 605
0.999973434440005 606
0.9999325896782195 607
0.9999785352962359 608
0.9997412468916259 609
0.9999987416017757 610
0.999999247981513 611
0.9995109639681773 612
0.9999999743323229 613
0.9990575994224032 614
0.9999995340771922 615
0.999998046146805 616
0.9999965405543008 617
0.9999998471433169 618
0.9999999744004978 619
0.9999999201104794 620
0.9997859426042381 621
0.999994904407325 622
0.999936975130182 623
0.9999998404196871 624
0.9999936537338046 625
0.999999810599378 626
0.9999644772566564 627
0.9999993219391723 628
0.9999999861625969 629
0.9997856730401661 630
0.9999524348015508 631
0.9999999169235536 632
0.99999967628415 633
0.9999842054616733 634
0.9999999751139061 635
0.9999993650565864 636
0.9999998924712389 637
0.999596683873952 638
0.9999960215105534 639
0.9999999800187233 640
0.9999888630536701 641
0.9999999543622071 642
0.9998082085029577 643
0.9999994415589409 644
0.9999968394270204 645
0.9999826132205414 646
0.9999893763536168 647
0.9999934105867516 648
0.9990202282995466 649
0.9999816889595363 650
0.9999990498906554 651
0.9999996846398131 652
0.9984883148814597 653
0.9999916505775069 654
0.9999879798527995 655
0.9999825293905772 656
0.9519209209706986 657
0.9999970864916071 658
0.9999998429339347 659
0.9999996213696732 660
0.9999996914076311 661
0.9999999692424039 662
0.9999721538011193 663
0.9999995138785218 664
0.9999987869151041 665
0.9999996571300824 666
0.9999785292977427 667
0.9999371662874685 668
0.9999998098535172 669
0.9999999410586621 670
0.9999995797724698 671
0.9999999610440847 672
0.9999996310937965 673
0.9998819758956649 674
0.9999942174776162 675
0.9999520667361969 676
0.9999998896151586 677
0.9999999627128794 678
0.9999997514206329 679
0.999999923967166 680
0.9999999021014188 681
0.9999823011166069 682
0.9999987455669369 683
0.9999732143774152 684
0.9999259436988494 685
0.9999997057586862 686
0.9998356189574914 687
0.9999998641258827 688
0.9999998984897335 689
0.9985382468533304 690
0.9999993407470296 691
0.9999999461796938 692
0.9999911139982514 693
0.9999933101311199 694
0.9999972090153972 695
0.9999561684969802 696
0.9990459963712778 697
0.9999969597693923 698
0.9999997691618023 699
0.9999997528569097 700
0.9999994279747503 701
0.999999792174509 702
0.9999993392387154 703
0.9999999527239883 704
0.9999999589225163 705
0.9999998603404321 706
0.9999996154105476 707
0.9999994070745608 708
0.9999998598153994 709
0.9999998419120549 710
0.9999996031990638 711
0.9998973316212596 712
0.9999979484530553 713
0.9999965303234276 714
0.9999838978761644 715
0.9999991563279256 716
0.9999995675336159 717
0.9999945191031133 718
0.9993819421275236 719
0.9999750519205298 720
0.9999919637517425 721
0.9999983085360779 722
0.9999930154441555 723
0.9996304503967824 724
0.99893677189258 725
0.9994665339916186 726
0.9999864101179986 727
0.9999923596515686 728
0.9998661476605026 729
0.9999999406514815 730
0.9999995659753305 731
0.9999663487434831 732
0.9999982510780993 733
0.9999843663983375 734
0.999990534582976 735
0.9999997980808143 736
0.9999793015393288 737
0.9999998748778245 738
0.9999996706368569 739
0.9999998455575199 740
0.9999999736855837 741
0.9999990841577309 742
0.9997329504210013 743
0.9999982740090555 744
0.9999989368213025 745
0.9999831682315669 746
0.999999726122355 747
0.9999999843271578 748
0.9998848979866561 749
0.9999930511687419 750
0.9999998130149532 751
0.9999949796739799 752
0.999984793415521 753
0.9999941838582799 754
0.9999987425919334 755
0.9999847112040068 756
0.9999871843463791 757
0.999999876756542 758
0.999995958109225 759
0.9999999370751239 760
0.9999899937614223 761
0.9999998898929818 762
0.9999972109957832 763
0.9999223417057607 764
0.9999999242082692 765
0.9999794280540791 766
0.9999994175988972 767
0.9999917157592909 768
0.9997551550454231 769
0.9996915303124695 770
0.9999751583422231 771
0.999999968454041 772
0.9999678451773799 773
0.9999949805991433 774
0.9999908458770554 775
0.9999980544375978 776
0.999943099941717 777
0.9999999791402154 778
0.9999944124374959 779
0.9999632197794677 780
0.999999911797114 781
0.9990002327685555 782
0.9999996918300931 783
0.9999996737587288 784
0.9999999732107936 785
0.99999955677781 786
0.9998115128748993 787
0.9999974857976903 788
0.9998638525061602 789
0.9999989942612545 790
0.9999970618711863 791
0.9999999830098902 792
0.9999438500043653 793
0.9999995715696327 794
0.9999983922774593 795
0.9999985176991092 796
0.9999997714769294 797
0.999999793063627 798
0.999963068942073 799
0.9999909951770293 800
0.9999896974822563 801
0.9999999230920372 802
0.9999945469884157 803
0.9999942613116641 804
0.9999962890230236 805
0.9999998627031745 806
0.9999999594542357 807
0.9998837327946476 808
0.9847484997801192 809
0.9999947641248493 810
0.9999998891992208 811
0.9999121172261408 812
0.9999943734146911 813
0.9999912787443137 814
0.9993135736325779 815
0.9999995799652974 816
0.9999994874265135 817
0.9999999431796566 818
0.9999714112911238 819
0.9999869849902391 820
0.9999998765333445 821
0.9999999167495639 822
0.9999997933853286 823
0.9999995540612324 824
0.999999810599378 825
0.9999811262881775 826
0.9999999190885516 827
0.9999891942376966 828
0.9999992238589808 829
0.999999542497836 830
0.999997110988966 831
0.9999997798573533 832
0.9999997728424952 833
0.9999999742361585 834
0.9999998342171391 835
0.9999999797792974 836
0.9999976939796139 837
0.9999993131063027 838
0.999999247981513 839
0.9999977014192046 840
0.9999967071491803 841
0.9999997699306905 842
0.9999997925292613 843
0.9999984185293354 844
0.9999666534302313 845
0.9999545331741251 846
0.999999965389436 847
0.9999997262993011 848
0.9999996236289118 849
0.9999999323357144 850
0.9999992473019774 851
0.9999999781130814 852
0.9999895249722596 853
0.9999146575623848 854
0.9999621901445178 855
0.9999999829010137 856
0.9999998779867817 857
0.9999999080351103 858
0.9999999772352208 859
0.9999996512224802 860
0.9999998714656114 861
0.9999994516036906 862
0.9999861523607764 863
0.9999997178994885 864
0.9674764018942937 865
0.9999999452410244 866
0.999960042703959 867
0.9999997592705128 868
0.9999997231866327 869
0.9998600048964378 870
0.9999997547068901 871
0.9999938110675253 872
0.99999648706435 873
0.9999999367964937 874
0.9998351384280513 875
0.999999029326123 876
0.9999263343049313 877
0.9999996145258037 878

In [68]:
get_similar_households(17)

household_key
176     0.999999
588     0.999999
963     0.999999
2093    0.999999
1299    0.999999
Name: 17, dtype: float64

In [69]:
sub_commodity_purchases.head(10)

   household_key              SUB_COMMODITY_DESC  total_quantity  total_sales
0              1                ADULT ANALGESICS               3        16.67
1              1                    ADULT CEREAL               2         7.48
2              1                AEROSOL TOPPINGS               1         1.99
3              1             AIR CARE - AEROSOLS               1         2.99
4              1              AIR CARE - CANDLES               6        16.73
5              1  AIR CARE - CONTINUOUS - NON EL               6        14.47
6              1    AIR CARE - CONTINUOUS ACTION               9        23.47
7              1               ALL FAMILY CEREAL              14        41.11
8              1                   ALUMINUM FOIL               4        10.33
9              1  ANTIPERSPIRANTS ONLY (ALL OTHE               5        18.75

In [70]:
def top5_recommendations(household_id):
    similar_households = get_similar_households(household_id)
    similar_households = similar_households.index
    similar_household_purchases = top_sub_commodities[top_sub_commodities["household_key"]
                                                      .isin(similar_households)][['household_key','SUB_COMMODITY_DESC', 
                                                                                  'total_quantity']]
    similar_household_purchases = similar_household_purchases.groupby(["SUB_COMMODITY_DESC"])["total_quantity"].sum().sort_values(ascending = False).reset_index().head(5)
    five_best_recommendations = similar_household_purchases["SUB_COMMODITY_DESC"].values
    for i in five_best_recommendations:
        print(i)

In [71]:
top5_recommendations(200)

SFT DRNK SNGL SRV BTL CARB (EX
CANDY BARS (SINGLES)(INCLUDING
SGL SV/VEND MACH SNACKS CHIP/P
SFT DRNK 2 LITER BTL CARB INCL
SFT DRNK MLT-PK BTL CARB (EXCP